// Sinh src/content/search-index.generated.ts — corpus tìm kiếm thật cho command
// palette (Ctrl+K), khác với search-actions.ts (chỉ ~9 shortcut cố định).
// Đọc từ các file đã generate sẵn (set18-*.ts, set18-slugs.generated.ts,
// lessons.generated.ts) — KHÔNG cần kết nối Neon. Chạy lại sau khi
// `pnpm db:pull` (đổi dữ liệu Set18) hoặc `pnpm content:sync` (đổi bài học).
//
// Chạy: pnpm content:search-index

import { writeFileSync } from 'node:fs';
import { toSlug } from '../../src/lib/slug';
import { set18Champions } from '../../src/content/set18/set18-champions';
import { set18Traits } from '../../src/content/set18/set18-traits';
import { set18Augments } from '../../src/content/set18/set18-augments';
import { set18Wisps } from '../../src/content/set18/set18-wisps';
import { getChampionSlug, getTraitSlug, getAugmentSlug, getWispSlug } from '../../src/content/set18/set18-lookup';
import { lessons } from '../../src/content/lessons';

type SearchIndexKind = 'champion' | 'trait' | 'wisp' | 'augment' | 'lesson';

type SearchIndexEntry = {
  id: string;
  kind: SearchIndexKind;
  label: string;
  sublabel: string;
  href: string;
  folded: string;
};

function entry(kind: SearchIndexKind, id: string, label: string, sublabel: string, href: string, extraTerms: string[] = []): SearchIndexEntry {
  const folded = toSlug([label, sublabel, ...extraTerms].filter(Boolean).join(' ')).replace(/-/g, ' ');
  return { id, kind, label, sublabel, href, folded };
}

const entries: SearchIndexEntry[] = [];

// href trỏ tới trang SECTION (lưới tương tác) kèm ?focus=slug, KHÔNG phải trang
// chi tiết đơn lẻ /mua-18/{kind}/{slug} — bấm kết quả tìm kiếm sẽ cuộn tới đúng
// thẻ trong lưới, giữ nguyên bối cảnh lọc/so sánh xung quanh (xem hiệu ứng cuộn
// trong Set18Codex.tsx). Trang chi tiết đơn lẻ vẫn tồn tại và có trong sitemap —
// chỉ không phải nơi search điều hướng tới.
for (const champion of set18Champions) {
  const slug = getChampionSlug(champion);
  if (!slug) continue;
  entries.push(
    entry('champion', `champion:${slug}`, champion.name, `${champion.costLabel} · ${champion.role}`, `/mua-18/chi-tiet-tuong?focus=${slug}`, champion.traits),
  );
}

for (const trait of set18Traits) {
  const slug = getTraitSlug(trait);
  if (!slug) continue;
  entries.push(entry('trait', `trait:${slug}`, trait.vi, `${trait.typeVi} · ${trait.name}`, `/mua-18/chi-tiet-toc-he?focus=${slug}`, [trait.name]));
}

for (const wisp of set18Wisps) {
  const slug = getWispSlug(wisp);
  if (!slug) continue;
  entries.push(entry('wisp', `wisp:${slug}`, wisp.nameVi, `Tinh Linh · ${wisp.categoryVi}`, `/mua-18/tinh-linh?focus=${slug}`, [wisp.name]));
}

for (const augment of set18Augments) {
  const slug = getAugmentSlug(augment);
  if (!slug) continue;
  entries.push(
    entry('augment', `augment:${slug}`, augment.nameVi, `Nâng cấp ${augment.rarity} · ${augment.categoryVi}`, `/mua-18/nang-cap?focus=${slug}`, [augment.name]),
  );
}

for (const lesson of lessons) {
  entries.push(entry('lesson', `lesson:${lesson.slug}`, lesson.title, lesson.module, `/kien-thuc-nen-tang/${lesson.slug}`, [lesson.shortTitle]));
}

writeFileSync(
  'src/content/search-index.generated.ts',
  [
    '// GENERATED FILE — do not edit by hand.',
    '// Generated by Website/scripts/db/generate-search-index.ts.',
    '// Chạy lại sau `pnpm db:pull` hoặc `pnpm content:sync` (pnpm content:search-index).',
    '',
    "export type SearchIndexKind = 'champion' | 'trait' | 'wisp' | 'augment' | 'lesson';",
    '',
    'export type SearchIndexEntry = {',
    '  id: string;',
    '  kind: SearchIndexKind;',
    '  label: string;',
    '  sublabel: string;',
    '  href: string;',
    '  /** Chuỗi đã bỏ dấu + lowercase, gộp label+sublabel+alias — dùng để so khớp query đã bỏ dấu. */',
    '  folded: string;',
    '};',
    '',
    `export const searchIndex: SearchIndexEntry[] = ${JSON.stringify(entries)};`,
    '',
  ].join('\n'),
);

console.log(`✓ search-index.generated.ts: ${entries.length} mục`);
