// Sinh lại src/content/set18/set18-slugs.generated.ts từ
// set18-entity-index.ts đã có sẵn trong repo — KHÔNG cần kết nối Neon.
// Dùng khi entity-index vừa đổi (sau `pnpm db:pull`) nhưng chỉ muốn build lại
// slug mà không kéo lại toàn bộ DB. `pnpm db:pull` tự gọi logic này rồi, script
// này chỉ để chạy tay/offline.
//
// Chạy: pnpm db:generate-slugs

import { set18EntityIndex } from '../../src/content/set18/set18-entity-index';
import { buildSet18Slugs, writeSet18Slugs } from './lib/build-set18-slugs';

const entries = buildSet18Slugs(set18EntityIndex);
writeSet18Slugs(entries, 'Generated by Website/scripts/db/generate-set18-slugs.ts từ set18-entity-index.ts.');
