// Đồng bộ NGƯỢC: đọc Postgres (Neon) rồi ghi đè các file nội dung tĩnh trong
// src/content/set18/*.ts + src/content/patch-notes.generated.ts. Đây là bước
// "ghi đè" sau khi sửa dữ liệu trong DB (qua apply-patch-draft.ts hoặc UPDATE
// trực tiếp) — chạy xong thì `git diff` để duyệt trước khi commit/deploy, giữ
// đúng quy trình review đã dùng từ trước khi có DB.
//
// Chạy: pnpm db:pull

import { writeFileSync } from 'node:fs';
import { asc } from 'drizzle-orm';
import { db } from '../../src/db/client';
import {
  set18Champions,
  set18Traits,
  set18Augments,
  set18Wisps,
  set18Items,
  patchReports as patchReportsTable,
  patchEntries as patchEntriesTable,
} from '../../src/db/schema';
import { buildSet18Slugs, writeSet18Slugs } from './lib/build-set18-slugs';

function omitKeys<T extends Record<string, unknown>>(obj: T, keys: (keyof T)[]): T {
  const copy = { ...obj };
  for (const k of keys) delete copy[k];
  return copy;
}

/** Xoá field optional (kiểu `foo?: X`, KHÔNG phải `foo: X | null`) khi giá trị
 * là null — gán thẳng null vào field optional sẽ vỡ type (X | undefined, không
 * nhận null). Field nullable thật sự (vd Set18Wisp.cost: number | null) không
 * được liệt vào đây, phải giữ nguyên null. */
function stripNullOptionals<T extends Record<string, unknown>>(obj: T, optionalKeys: (keyof T)[]): T {
  const copy = { ...obj };
  for (const k of optionalKeys) {
    if (copy[k] === null) delete copy[k];
  }
  return copy;
}

function writeGenerated(path: string, header: string[], exportLines: string | string[]) {
  const lines = Array.isArray(exportLines) ? exportLines : [exportLines];
  writeFileSync(path, [...header, '', ...lines, ''].join('\n'));
}

async function pullChampions() {
  const rows = await db
    .select()
    .from(set18Champions)
    .orderBy(asc(set18Champions.cost), asc(set18Champions.name));
  const data = rows.map((r) => stripNullOptionals(omitKeys(r, ['id', 'updatedAt']), ['forms', 'nicknameVi']));
  writeGenerated(
    'src/content/set18/set18-champions.ts',
    ['// GENERATED FILE — do not edit by hand.', '// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_champions trên Neon.', '', "import type { Set18Champion } from './set18-types';"],
    [
      `export const set18Champions: Set18Champion[] = ${JSON.stringify(data)};`,
      'export const set18ChampionByName = new Map(set18Champions.map((champion) => [champion.name, champion]));',
    ],
  );
  console.log(`✓ set18-champions.ts: ${data.length} dòng`);
  return rows;
}

async function pullTraits() {
  const rows = await db.select().from(set18Traits).orderBy(asc(set18Traits.name));
  const data = rows.map((r) =>
    stripNullOptionals(omitKeys(r, ['id', 'updatedAt']), ['infoChips', 'bounties', 'subEffects', 'note', 'activation', 'wide']),
  );
  writeGenerated(
    'src/content/set18/set18-traits.ts',
    ['// GENERATED FILE — do not edit by hand.', '// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_traits trên Neon.', '', "import type { Set18Trait, Set18TraitType } from './set18-types';"],
    [
      `export const set18Traits: Set18Trait[] = ${JSON.stringify(data)};`,
      'export const set18TraitByName = new Map(set18Traits.map((trait) => [trait.name, trait]));',
      'export const set18TraitsByType = (type: Set18TraitType) => set18Traits.filter((trait) => trait.type === type);',
    ],
  );
  console.log(`✓ set18-traits.ts: ${data.length} dòng`);
  return rows;
}

async function pullAugments() {
  const rows = await db.select().from(set18Augments).orderBy(asc(set18Augments.name));
  const data = rows.map((r) => omitKeys(r, ['id', 'updatedAt']));
  writeGenerated(
    'src/content/set18/set18-augments.ts',
    ['// GENERATED FILE — do not edit by hand.', '// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_augments trên Neon.', '', "import type { Set18Augment } from './set18-types';"],
    `export const set18Augments: Set18Augment[] = ${JSON.stringify(data)};`,
  );
  console.log(`✓ set18-augments.ts: ${data.length} dòng`);
  return rows;
}

async function pullWisps() {
  const rows = await db.select().from(set18Wisps).orderBy(asc(set18Wisps.tier), asc(set18Wisps.name));
  const data = rows.map((r) => omitKeys(r, ['id', 'updatedAt']));
  writeGenerated(
    'src/content/set18/set18-wisps.ts',
    ['// GENERATED FILE — do not edit by hand.', '// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_wisps trên Neon.', '', "import type { Set18Wisp } from './set18-types';"],
    `export const set18Wisps: Set18Wisp[] = ${JSON.stringify(data)};`,
  );
  console.log(`✓ set18-wisps.ts: ${data.length} dòng`);
  return rows;
}

async function pullItems() {
  const rows = await db.select().from(set18Items).orderBy(asc(set18Items.category), asc(set18Items.name));
  const data = rows.map((r) => stripNullOptionals(omitKeys(r, ['id', 'updatedAt']), ['statLine', 'statBadges']));
  writeGenerated(
    'src/content/set18/set18-items.ts',
    ['// GENERATED FILE — do not edit by hand.', '// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_items trên Neon.', '', "import type { Set18Item } from './set18-types';"],
    [
      `export const set18Items: Set18Item[] = ${JSON.stringify(data)};`,
      'export const set18ItemByApiName = new Map(set18Items.map((item) => [item.apiName, item]));',
    ],
  );
  console.log(`✓ set18-items.ts: ${data.length} dòng`);
  return rows;
}

type EntityIndexEntry = {
  id: string;
  kind: 'champion' | 'trait' | 'augment' | 'wisp';
  name: string;
  nameVi?: string;
  icon: string;
  accent?: string;
  cost?: number;
  rarity?: string;
};

async function pullEntityIndex(
  champions: { id: string; name: string; image: string; cost: number; costColor: string }[],
  traits: { id: string; name: string; vi: string; icon: string; accent: string }[],
  augments: { id: string; name: string; nameVi: string; icon: string; rarityColor: string; rarity: string }[],
  wisps: { id: string; name: string; nameVi: string; categoryIcon: string }[],
) {
  const entries: EntityIndexEntry[] = [
    ...champions.map((c) => ({ id: c.id, kind: 'champion' as const, name: c.name, icon: c.image, cost: c.cost, accent: c.costColor })),
    ...traits.map((t) => ({ id: t.id, kind: 'trait' as const, name: t.name, nameVi: t.vi, icon: t.icon, accent: t.accent })),
    ...augments.map((a) => ({ id: a.id, kind: 'augment' as const, name: a.name, nameVi: a.nameVi, icon: a.icon, accent: a.rarityColor, rarity: a.rarity })),
    ...wisps.map((w) => ({ id: w.id, kind: 'wisp' as const, name: w.name, nameVi: w.nameVi, icon: w.categoryIcon })),
  ];
  writeFileSync(
    'src/content/set18/set18-entity-index.ts',
    [
      '// GENERATED FILE — do not edit by hand.',
      '// Generated by Website/scripts/db/pull-set18.ts từ 4 bảng set18_* trên Neon.',
      '',
      "import type { Set18EntityIndexEntry, Set18EntityKind } from './set18-types';",
      '',
      `export const set18EntityIndex: Set18EntityIndexEntry[] = ${JSON.stringify(entries)};`,
      'export const set18EntityById = new Map(set18EntityIndex.map((entry) => [entry.id, entry]));',
      'export const set18EntityByKindAndName = new Map(set18EntityIndex.map((entry) => [`${entry.kind}:${entry.name}`, entry]));',
      'export function findSet18Entity(kind: Set18EntityKind, name: string) {',
      '  return set18EntityByKindAndName.get(`${kind}:${name}`);',
      '}',
      '',
    ].join('\n'),
  );
  console.log(`✓ set18-entity-index.ts: ${entries.length} dòng`);
  return entries;
}

const ENTRY_OPTIONAL_KEYS = ['entityId', 'note', 'icon', 'cost', 'rarity', 'wispTier', 'wispCategory', 'breakpoint', 'breakpointStyle', 'changes'] as const;
const REPORT_OPTIONAL_KEYS = ['source', 'entitySet', 'summaryOrigin', 'rhythmVi', 'impacts'] as const;

async function pullPatchNotes() {
  // reportOrder tăng dần = cũ dần; 0 luôn là bản mới nhất (patchReports[0]).
  const reports = await db.select().from(patchReportsTable).orderBy(asc(patchReportsTable.reportOrder));
  const entries = await db.select().from(patchEntriesTable).orderBy(asc(patchEntriesTable.sortOrder));

  const data = reports.map((report) => {
    const reportEntries = entries
      .filter((e) => e.reportId === report.id)
      .map((e) => stripNullOptionals(omitKeys(e, ['reportId', 'sortOrder']), [...ENTRY_OPTIONAL_KEYS]));
    const reportFields = stripNullOptionals(omitKeys(report, ['createdAt', 'reportOrder']), [...REPORT_OPTIONAL_KEYS]);
    return { ...reportFields, entries: reportEntries };
  });

  writeFileSync(
    'src/content/patch-notes.generated.ts',
    [
      '// GENERATED FILE — do not edit by hand.',
      '// Generated by Website/scripts/db/pull-set18.ts từ bảng patch_reports/patch_entries trên Neon.',
      "// Sửa bằng cách sửa DB (qua scripts/db/apply-patch-draft.ts) rồi chạy lại 'pnpm db:pull'.",
      '',
      "import type { PatchReport } from './patch-notes';",
      '',
      `export const patchReports: PatchReport[] = ${JSON.stringify(data)};`,
      '',
    ].join('\n'),
  );
  console.log(`✓ patch-notes.generated.ts: ${data.length} bản vá, ${entries.length} mục`);
}

async function main() {
  const [champions, traits, augments, wisps] = await Promise.all([pullChampions(), pullTraits(), pullAugments(), pullWisps()]);
  await pullItems();
  const entityIndexEntries = await pullEntityIndex(champions, traits, augments, wisps);
  writeSet18Slugs(
    buildSet18Slugs(entityIndexEntries),
    'Generated by Website/scripts/db/pull-set18.ts từ set18-entity-index vừa build ở trên.',
  );
  await pullPatchNotes();
  console.log('\nĐã ghi đè file .ts từ DB — chạy `git diff` trong Website/ để duyệt trước khi commit.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
