// Draft bản vá PBE — nội dung/số liệu đã được duyệt trong
// Website/pbe-notes/Patch_TFT18.1ab-PBE-moderate-balance-pass.md (đăng
// August 10th, 2026 - 12:00 PDT, tiếp theo bản 18.1aa 07/08). File này chỉ
// chuyển nội dung đó thành PatchReport để áp vào DB (pnpm db:apply-patch) rồi
// pull ra patch-notes.generated.ts (pnpm db:pull).
import type { PatchReport } from '../../../src/content/patch-notes';

const report: PatchReport = {
  id: 'patch-tft18-1ab',
  version: 'PBE 10/08/2026 (18.1ab)',
  title: 'Moderate pass, balance',
  author: 'Baron TFT (dịch)',
  source: {
    label: 'PBE — TheTruexy (dev PBE chính thức)',
    url: 'https://x.com/TheTruexy/status/2086843790518829102',
  },
  entitySet: 18,
  dateVi: '10/08/2026',
  summaryVi:
    'Bản vá cân bằng tương đối lớn, tập trung thu hẹp khoảng cách 4/5 vàng: nerf loạt tướng 5 vàng (Kennen, Draven, Ivern, Lux) và Blossom Charms; buff Ashe, Camille, Hunter; 6 Blackthorn tạm chưa đổi vì đang chờ reshape lại tộc hệ.',
  summaryOrigin: 'official',
  entries: [
    // ── Tướng — 1 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0810ab-akali',
      category: 'champion',
      kind: 'nerf',
      name: 'Akali',
      cost: 1,
      entityId: 'champion:tft18_akali',
      changes: [{ label: 'Sát thương chiêu (AP)', from: '170/255/385 AP', to: '155/235/385 AP' }],
    },
    {
      id: 'pbe0810ab-akali-ad',
      category: 'champion',
      kind: 'buff',
      name: 'Akali',
      cost: 1,
      entityId: 'champion:tft18_akali',
      changes: [{ label: 'Sát thương chiêu (AD)', from: '145/220/325 AD', to: '145/220/345 AD' }],
    },
    {
      id: 'pbe0810ab-camille',
      category: 'champion',
      kind: 'buff',
      name: 'Camille',
      cost: 1,
      entityId: 'champion:tft18_camille',
      changes: [
        { label: 'Khiên', from: '60/85/135', to: '60/85/160' },
        { label: 'Sát thương chiêu', from: '160/240/390 AD', to: '160/240/410 AD' },
      ],
    },
    {
      id: 'pbe0810ab-leona',
      category: 'champion',
      kind: 'buff',
      name: 'Leona',
      cost: 1,
      entityId: 'champion:tft18_leona',
      changes: [{ label: 'Thời gian Chống Chịu', from: '10s', to: '12s' }],
    },
    {
      id: 'pbe0810ab-ornn',
      category: 'champion',
      kind: 'nerf',
      name: 'Ornn',
      cost: 1,
      entityId: 'champion:tft18_ornn',
      changes: [
        { label: 'Khiên', from: '400/480/600 AP', to: '400/460/550 AP' },
        { label: 'Ngưỡng sát thương nhận (Artifact thứ 2)', from: '220,000', to: '235,000' },
      ],
    },

    // ── Tướng — 2 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0810ab-murkwolf',
      category: 'champion',
      kind: 'buff',
      name: 'Murkwolf',
      cost: 2,
      entityId: 'champion:tft18_murkwolf',
      changes: [{ label: 'Chí Mạng cộng thêm (Alpha Mark)', from: '25-50%', to: '25-75%' }],
    },
    {
      id: 'pbe0810ab-gromp',
      category: 'champion',
      kind: 'buff',
      name: 'Gromp',
      cost: 2,
      entityId: 'champion:tft18_gromp',
      changes: [{ label: 'SMCK hoặc Sức mạnh phép (Alpha Mark)', from: '25%', to: '30%' }],
    },
    {
      id: 'pbe0810ab-yunara',
      category: 'champion',
      kind: 'nerf',
      name: 'Yunara',
      cost: 2,
      entityId: 'champion:tft18_yunara',
      changes: [{ label: 'Sát thương chiêu', from: '170/255/450 AD', to: '170/255/415 AD' }],
    },

    // ── Tướng — 3 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0810ab-hecarim',
      category: 'champion',
      kind: 'nerf',
      name: 'Hecarim',
      cost: 3,
      entityId: 'champion:tft18_hecarim',
      changes: [{ label: 'Hồi máu', from: '400/500/720 AP', to: '375/475/685 AP' }],
    },
    {
      id: 'pbe0810ab-kogmaw',
      category: 'champion',
      kind: 'nerf',
      name: "Kog'Maw",
      cost: 3,
      entityId: 'champion:tft18_kogmaw',
      changes: [
        { label: 'Sát thương chiêu (AP)', from: '170/255/450 AP', to: '160/240/415 AP' },
        { label: 'Sát thương chiêu (AD)', from: '155/235/400 AD', to: '145/220/375 AD' },
      ],
    },
    {
      id: 'pbe0810ab-rengar',
      category: 'champion',
      kind: 'nerf',
      name: 'Rengar',
      cost: 3,
      entityId: 'champion:tft18_rengar',
      changes: [{ label: 'Sát thương chiêu', from: '270/405/650 AD', to: '255/385/615 AD' }],
    },

    // ── Tướng — 4 vàng ──────────────────────────────────────────────
    {
      // Ảnh gốc đánh dấu mũi tên buff (▲) cho dòng này nhưng số liệu giảm —
      // người dùng xác nhận đây là nguồn đánh dấu nhầm hướng, thực chất là nerf.
      id: 'pbe0810ab-aphelios',
      category: 'champion',
      kind: 'nerf',
      name: 'Aphelios',
      cost: 4,
      entityId: 'champion:tft18_aphelios',
      changes: [{ label: 'Tốc Đánh cộng thêm mỗi lượt đánh phụ', from: '45%', to: '35%' }],
    },
    {
      id: 'pbe0810ab-brambleback',
      category: 'champion',
      kind: 'buff',
      name: 'Brambleback',
      cost: 4,
      entityId: 'champion:tft18_brambleback',
      changes: [{ label: 'Xuyên Giáp Phép', from: '20%', to: '30%' }],
    },
    {
      // Giảm mana giúp kỹ năng ra sớm hơn, khống chế sớm hơn — người dùng
      // xác nhận đây là buff dù ảnh gốc không đánh dấu mũi tên.
      id: 'pbe0810ab-lillia',
      category: 'champion',
      kind: 'buff',
      name: 'Lillia',
      cost: 4,
      entityId: 'champion:tft18_lillia',
      changes: [{ label: 'Năng lượng', from: '50/150', to: '40/140' }],
    },
    {
      // Curse DoT tăng — người dùng xác nhận là buff dù ảnh gốc không đánh
      // dấu mũi tên.
      id: 'pbe0810ab-morgana',
      category: 'champion',
      kind: 'buff',
      name: 'Morgana',
      cost: 4,
      entityId: 'champion:tft18_morgana',
      changes: [{ label: 'Sát thương theo thời gian (Curse)', from: '18/27', to: '22/33' }],
    },
    {
      id: 'pbe0810ab-nidalee',
      category: 'champion',
      kind: 'buff',
      name: 'Nidalee',
      cost: 4,
      entityId: 'champion:tft18_nidalee',
      changes: [{ label: 'Sát thương chiêu (AD)', from: '215/325 AD', to: '225/340 AD' }],
    },

    // ── Tướng — 5 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0810ab-ashe',
      category: 'champion',
      kind: 'buff',
      name: 'Ashe',
      cost: 5,
      entityId: 'champion:tft18_ashe',
      changes: [{ label: 'Sát thương chiêu', from: '400/600 AD', to: '440/660 AD' }],
    },
    {
      // Dash Damage và Shield tăng số liệu, nhưng Spell Damage (nguồn sát
      // thương chính) giảm mạnh áp đảo — người dùng xác nhận tổng thể vẫn
      // là nerf, gắn kind: 'nerf' cho cả 3 dòng.
      id: 'pbe0810ab-kennen',
      category: 'champion',
      kind: 'nerf',
      name: 'Kennen',
      cost: 5,
      entityId: 'champion:tft18_kennen',
      changes: [
        { label: 'Sát thương lướt (Dash)', from: '50/75 AP', to: '80/120 AP' },
        { label: 'Sát thương chiêu', from: '525/785 AP', to: '450/675 AP' },
        { label: 'Khiên', from: '225/300 AP', to: '250/350 AP' },
      ],
    },
    {
      id: 'pbe0810ab-draven',
      category: 'champion',
      kind: 'nerf',
      name: 'Draven',
      cost: 5,
      entityId: 'champion:tft18_draven',
      changes: [
        { label: 'Sát thương Chảy Máu (Bleed)', from: '150/225 AD', to: '140/210 AD' },
        { label: 'Sát thương chiêu gốc', from: '180/270 AD', to: '130/200 AD' },
        { label: 'Tỉ lệ nhắm mục tiêu ngẫu nhiên trong tầm', from: '85%', to: '70%' },
      ],
    },
    {
      id: 'pbe0810ab-ivern',
      category: 'champion',
      kind: 'nerf',
      name: 'Ivern',
      cost: 5,
      entityId: 'champion:tft18_ivern',
      changes: [
        { label: 'Tốc Đánh gốc', from: '0.85', to: '0.8' },
        { label: 'Giáp/Kháng Phép (Rock Hex)', from: '12/15', to: '8/12' },
        { label: 'Hồi Năng Lượng (Water Hex)', from: '2/3', to: '1/2' },
        { label: 'Máu tối đa cộng thêm (Tree Hex)', from: '6/12%', to: '8/12%' },
        { label: 'Tốc Đánh cộng thêm (Flower Hex)', from: '10/15%', to: '8/12%' },
        { label: 'Số hạt giống Greenfather mỗi giao tranh', from: '4', to: '3' },
      ],
    },
    {
      // Riêng dòng Khiên là buff (số liệu tăng) giữa các thay đổi còn lại
      // đều là nerf — người dùng xác nhận đúng là một điểm tăng cục bộ,
      // không phải lỗi nguồn.
      id: 'pbe0810ab-ivern-shield',
      category: 'champion',
      kind: 'buff',
      name: 'Ivern',
      cost: 5,
      entityId: 'champion:tft18_ivern',
      changes: [{ label: 'Khiên', from: '150/275 AP', to: '165/300 AP' }],
    },
    {
      id: 'pbe0810ab-lux',
      category: 'champion',
      kind: 'nerf',
      name: 'Lux',
      cost: 5,
      entityId: 'champion:tft18_lux',
      changes: [
        { label: 'Máu cộng thêm (Elderwood)', from: '4%', to: '2.5%' },
        { label: 'Thời gian sát thương cộng thêm (Lunar)', from: '6s', to: '4s' },
        { label: 'Sát thương cộng thêm (Lunar)', from: '12%', to: '10%' },
        { label: 'Sát thương cộng thêm (Blossom)', from: '15%', to: '10%' },
      ],
    },

    // ── Tướng 3 sao ───────────────────────────────────────────────
    {
      id: 'pbe0810ab-alune-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Alune',
      cost: 5,
      entityId: 'champion:tft18_alune',
      note: '3 sao',
      changes: [{ label: 'Sát thương Moon', from: '6500 AP', to: '7500 AP' }],
    },
    {
      id: 'pbe0810ab-draven-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Draven',
      cost: 5,
      entityId: 'champion:tft18_draven',
      note: '3 sao',
      changes: [
        { label: 'Thời gian choáng', from: '10s', to: '15s' },
        { label: 'Sát thương Chảy Máu', from: '1000 AD', to: '3000 AD' },
      ],
    },
    {
      id: 'pbe0810ab-gnar-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Gnar',
      cost: 5,
      entityId: 'champion:tft18_gnar',
      note: '3 sao',
      changes: [
        { label: 'Thời gian choáng', from: '5s', to: '15s' },
        { label: 'Sát thương lao (Leap)', from: '1500 AD', to: '2000 AD' },
      ],
    },
    {
      id: 'pbe0810ab-kennen-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Kennen',
      cost: 5,
      entityId: 'champion:tft18_kennen',
      note: '3 sao',
      changes: [
        { label: 'Sát thương lướt (Dash)', from: '300 AP', to: '1500 AP' },
        { label: 'Sát thương chiêu', from: '3000 AP', to: '5000 AP' },
      ],
    },
    {
      id: 'pbe0810ab-taric-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Taric',
      cost: 5,
      entityId: 'champion:tft18_taric',
      note: '3 sao',
      changes: [{ label: 'Sát thương chuẩn (% máu tối đa mục tiêu)', from: '15%', to: '25%' }],
    },
    {
      id: 'pbe0810ab-aphelios-3star',
      category: 'champion',
      kind: 'nerf',
      name: 'Aphelios',
      cost: 4,
      entityId: 'champion:tft18_aphelios',
      note: '3 sao',
      changes: [{ label: 'Sát thương Swipe', from: '11000 AD', to: '850 AD' }],
    },
    {
      id: 'pbe0810ab-brambleback-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Brambleback',
      cost: 4,
      entityId: 'champion:tft18_brambleback',
      note: '3 sao',
      changes: [{ label: 'Xuyên Giáp', from: '20%', to: '50%' }],
    },
    {
      id: 'pbe0810ab-sivir-3star',
      category: 'champion',
      kind: 'nerf',
      name: 'Sivir',
      cost: 4,
      entityId: 'champion:tft18_sivir',
      note: '3 sao',
      changes: [{ label: 'Sát thương Boomerang phụ', from: '50%', to: '40%' }],
    },
    {
      id: 'pbe0810ab-ezreal-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Ezreal',
      cost: 4,
      entityId: 'champion:tft18_ezreal',
      note: '3 sao',
      changes: [{ label: 'Sát thương đòn đánh nhỏ', from: '900 AD', to: '1200 AD' }],
    },
    {
      id: 'pbe0810ab-soraka-3star',
      category: 'champion',
      kind: 'buff',
      name: 'Soraka',
      cost: 4,
      entityId: 'champion:tft18_soraka',
      note: '3 sao',
      changes: [
        {
          label: 'Cơ chế',
          from: 'Đánh 1 lần',
          to: 'Đánh 2 lần (double cast) — lần 2 xảy ra ngay khi lần đầu vốn sẽ unlock Soraka, tự chọn mục tiêu mới nếu còn địch khác trên bàn',
        },
      ],
    },

    // ── Tộc hệ ──────────────────────────────────────────────────────
    {
      id: 'pbe0810ab-trait-blossom',
      category: 'trait',
      kind: 'nerf',
      name: 'Blossom',
      entityId: 'trait:blossom',
      breakpoint: '9',
      changes: [{ label: 'SMCK/Sức mạnh phép cộng thêm', from: '50%', to: '45%' }],
    },
    {
      id: 'pbe0810ab-trait-blossom-charms',
      category: 'trait',
      kind: 'nerf',
      name: 'Blossom',
      note: 'Bùa (Charms)',
      entityId: 'trait:blossom',
      changes: [
        { label: 'All Fours — Vàng thưởng', from: '4g', to: '2g' },
        { label: 'All Threes — Vàng thưởng', from: '3g', to: '2g' },
        { label: 'All Twos — Vàng thưởng', from: '2g', to: '1g' },
        { label: 'Barter — Vàng thưởng', from: '300%', to: '250%' },
        { label: 'Big Guns — Giá', from: '6g', to: '7g' },
        { label: 'Blood and Iron — Số lượt chết cần', from: '14', to: '16' },
        { label: 'Blood Ritual — Máu phải trả', from: '6', to: '8' },
        { label: 'Bronze Spoon — Giá', from: '3g', to: '2g' },
        { label: 'Bronze Spoon — Kinh nghiệm thưởng', from: '6', to: '4' },
        { label: 'Die Roll — Giá', from: '2g', to: '3g' },
        { label: 'Doodad Bag — Giá', from: '0g', to: '1g' },
        { label: 'Experienced — Giá', from: '1g', to: '0g' },
        { label: 'Experienced — Kinh nghiệm thưởng', from: '4', to: '2' },
        { label: 'Forest Twins — Giá', from: '4g', to: '5g' },
        { label: 'Healing Pool — Máu hồi', from: '9', to: '7' },
        { label: 'Killing Frenzy — Tốc Đánh', from: '120%', to: '140%' },
        { label: 'Knick-Knack Bag — Giá', from: '0g', to: '1g' },
        { label: 'Lesser Chaos — Giới hạn vàng', from: '2g', to: '1g' },
        { label: 'Lost Travelers — Giá', from: '3g', to: '4g' },
        { label: 'Radiant Mana Potion — Năng lượng khởi đầu', from: '25', to: '20' },
        { label: 'Radiant Mana Potion — Năng lượng cả đội', from: '20', to: '10' },
        { label: 'Rolling Bones — Tỉ lệ reroll', from: '65%', to: '60%' },
        { label: "Roly-Polys — Thời gian reroll", from: '15s', to: '16s' },
        { label: 'Smurfing — Giá', from: '5g', to: '6g' },
        { label: 'Thingamajig Bag — Giá', from: '0g', to: '1g' },
        { label: 'Three Me — Giá', from: '7g', to: '8g' },
      ],
    },
    {
      id: 'pbe0810ab-trait-hunter',
      category: 'trait',
      kind: 'buff',
      name: 'Hunter',
      entityId: 'trait:hunter',
      changes: [{ label: 'SMCK cộng thêm', from: '15/25/40/60%', to: '20/30/45/65%' }],
    },

    // ── Nâng cấp (Augments) ─────────────────────────────────────────
    {
      id: 'pbe0810ab-aug-capitalgainsi',
      category: 'augment',
      kind: 'nerf',
      name: 'Capital Gains I',
      entityId: 'augment:da_capitalgainsi',
      changes: [
        { label: 'Vàng lãi suất', from: '110%', to: '100%' },
        { label: 'Vàng khởi đầu', from: '2', to: '1' },
      ],
    },
    {
      // Vàng khởi đầu giảm mạnh (4→1) chiếm phần lớn giá trị cốt lõi của
      // augment này, phần lãi suất tăng chỉ bù lại một phần nhỏ — người
      // dùng xác nhận tổng thể vẫn là nerf.
      id: 'pbe0810ab-aug-capitalgainsii',
      category: 'augment',
      kind: 'nerf',
      name: 'Capital Gains II',
      entityId: 'augment:da_capitalgainsii',
      changes: [
        { label: 'Vàng lãi suất', from: '110%', to: '125%' },
        { label: 'Vàng khởi đầu', from: '4', to: '1' },
      ],
    },
    {
      id: 'pbe0810ab-aug-goinglong',
      category: 'augment',
      kind: 'nerf',
      name: 'Going Long',
      entityId: 'augment:da_goinglong',
      changes: [{ label: 'Vàng nhận ngay', from: '16', to: '10' }],
    },
    {
      id: 'pbe0810ab-aug-luxurysubscription',
      category: 'augment',
      kind: 'nerf',
      name: 'Luxury Subscription',
      entityId: 'augment:da_luxurysubscription',
      changes: [{ label: 'Vàng', from: '7', to: '3' }],
    },
    {
      id: 'pbe0810ab-aug-residualmagic',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic',
      entityId: 'augment:da_18_residualmagic',
      changes: [{ label: 'Máu khởi đầu', from: '80', to: '60' }],
    },
    {
      id: 'pbe0810ab-aug-residualmagicplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic +',
      entityId: 'augment:da_18_residualmagicplus',
      changes: [{ label: 'Máu khởi đầu', from: '100', to: '75' }],
    },
    {
      id: 'pbe0810ab-aug-residualmagicplusplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic ++',
      entityId: 'augment:da_18_residualmagicplusplus',
      changes: [{ label: 'Máu khởi đầu', from: '120', to: '90' }],
    },
    {
      id: 'pbe0810ab-aug-traitladder',
      category: 'augment',
      kind: 'nerf',
      name: 'Trait Ladder',
      entityId: 'augment:da_traitladder',
      note: 'Cashouts',
      changes: [
        { label: 'Mốc 7', from: "Thieve's Gloves", to: 'Đã gỡ bỏ' },
        { label: 'Mốc 9 (Item Anvil)', from: '1 Anvil đồ hoàn thiện', to: 'Đã gỡ bỏ' },
        { label: 'Mốc 9 (Reward 5 vàng)', from: '3x tướng 5 vàng', to: '3x tướng 5 vàng + 2g' },
        { label: 'Mốc 10', from: 'Không có', to: '1 Tactician item (Crown/Shield/Cape)' },
        { label: 'Mốc 11', from: 'Không có', to: '20 vàng' },
        { label: 'Mốc 12', from: 'Không có', to: '1 Lucky Item Chest + 3x tướng 4 vàng' },
        { label: 'Mốc 13', from: 'Không có', to: '4 thành phần + 1 remover + 8 vàng' },
        { label: 'Mốc 14', from: '3x Masterwork Upgrade', to: '1 Masterwork Upgrade + 10g' },
      ],
    },
  ],
};

export default report;
