// Draft bản vá PBE 06/08/2026. Nội dung/số liệu đã được duyệt trong
// Website/pbe-notes/2026-08-06-pbe-update.md — file này chỉ chuyển nội dung đó
// thành PatchReport để áp vào DB (pnpm db:apply-patch) rồi pull ra
// patch-notes.generated.ts (pnpm db:pull).
import type { PatchReport } from '../../../src/content/patch-notes';

const report: PatchReport = {
  id: 'patch-pbe-2026-08-06',
  version: 'PBE 06/08/2026',
  title: 'Cập nhật PBE 06/08/2026',
  author: 'Baron TFT (dịch)',
  source: {
    label: 'PBE — TheTruexy (dev PBE chính thức)',
    url: 'https://x.com/TheTruexy/status/2084290281445409232',
  },
  entitySet: 18,
  dateVi: '06/08/2026',
  summaryVi:
    'Bản cập nhật PBE điều chỉnh 28 tướng, 9 tộc hệ và 21 nâng cấp — trọng tâm là rework Diana và một loạt tướng bậc 1-3 được đẩy mạnh tay.',
  summaryOrigin: 'official',
  entries: [
    // ── Tướng — 1 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0806-camille',
      category: 'champion',
      kind: 'buff',
      name: 'Camille',
      cost: 1,
      entityId: 'champion:tft18_camille',
      changes: [
        { label: 'Sát thương chiêu', from: '160/240/360', to: '160/240/390' },
        { label: 'Khiên', from: '60/85/120', to: '60/85/135' },
      ],
    },
    {
      id: 'pbe0806-kobuko',
      category: 'champion',
      kind: 'buff',
      name: 'Kobuko',
      cost: 1,
      entityId: 'champion:tft18_kobuko',
      changes: [{ label: 'Hồi máu', from: '250/300/400', to: '265/315/430' }],
    },
    {
      id: 'pbe0806-ornn',
      category: 'champion',
      kind: 'nerf',
      name: 'Ornn',
      cost: 1,
      entityId: 'champion:tft18_ornn',
      changes: [{ label: 'Sát thương cần chặn để nhận tạo tác', from: '90000/200000/330000', to: '90000/220000/400000' }],
    },
    {
      id: 'pbe0806-pebbles',
      category: 'champion',
      kind: 'nerf',
      name: 'Pebbles',
      cost: 1,
      entityId: 'champion:tft18_pebbles',
      changes: [{ label: 'Sát thương mỗi giây', from: '160/240/360', to: '150/225/340' }],
    },
    {
      id: 'pbe0806-reksai',
      category: 'champion',
      kind: 'buff',
      name: "Rek'Sai",
      cost: 1,
      entityId: 'champion:tft18_reksai',
      changes: [{ label: 'Hồi máu mỗi giây', from: '9/12/15', to: '10/14/20' }],
    },

    // ── Tướng — 2 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0806-gromp',
      category: 'champion',
      kind: 'nerf',
      name: 'Gromp',
      cost: 2,
      entityId: 'champion:tft18_gromp',
      changes: [
        { label: 'Dạng SMCK — Sát thương mục tiêu chính', from: '340/510/765', to: '305/460/725' },
        { label: 'Dạng SMCK — Sát thương diện rộng', from: '110/165/250', to: '100/150/240' },
        { label: 'Dạng SMPT — Sát thương mục tiêu chính', from: '250/375/565', to: '225/340/535' },
        { label: 'Dạng SMPT — Sát thương diện rộng', from: '100/240/360', to: '145/220/345' },
      ],
    },
    {
      id: 'pbe0806-sejuani',
      category: 'champion',
      kind: 'buff',
      name: 'Sejuani',
      cost: 2,
      entityId: 'champion:tft18_sejuani',
      changes: [
        { label: 'Sát thương hình nón', from: '40/60/90', to: '90/135/205' },
        { label: 'Sát thương đập xuống', from: '70/105/160', to: '120/180/270' },
      ],
    },
    {
      id: 'pbe0806-warwick',
      category: 'champion',
      kind: 'buff',
      name: 'Warwick',
      cost: 2,
      entityId: 'champion:tft18_warwick',
      changes: [{ label: 'Sát thương chiêu', from: '180/270/405', to: '200/300/450' }],
    },

    // ── Tướng — 3 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0806-azir',
      category: 'champion',
      kind: 'buff',
      name: 'Azir',
      cost: 3,
      entityId: 'champion:tft18_azir',
      changes: [{ label: 'Sát thương chiêu', from: '48/72/115', to: '50/75/120' }],
    },
    {
      id: 'pbe0806-diana',
      category: 'champion',
      kind: 'rework',
      name: 'Diana',
      cost: 3,
      entityId: 'champion:tft18_diana',
      changes: [
        { label: 'Sát thương mỗi quả cầu', from: '125/190/300/530', to: '65/100/155/270' },
        { label: 'Số luồng đạn', from: '1 luồng, đơn mục tiêu', to: '6 luồng, chia đều mục tiêu trong 2 ô' },
        { label: 'Khiên', from: 'Suy giảm theo thời gian', to: 'Không suy giảm (bugfix)' },
      ],
    },
    {
      id: 'pbe0806-fiddlesticks',
      category: 'champion',
      kind: 'nerf',
      name: 'Fiddlesticks',
      cost: 3,
      entityId: 'champion:tft18_fiddlesticks',
      changes: [{ label: 'Hồi máu', from: '425/500/850', to: '395/470/790' }],
    },
    {
      id: 'pbe0806-hecarim',
      category: 'champion',
      kind: 'nerf',
      name: 'Hecarim',
      cost: 3,
      entityId: 'champion:tft18_hecarim',
      changes: [{ label: 'Hồi máu', from: '450/550/800', to: '400/500/720' }],
    },
    {
      id: 'pbe0806-khazix',
      category: 'champion',
      kind: 'buff',
      name: "Kha'Zix",
      cost: 3,
      entityId: 'champion:tft18_khazix',
      changes: [
        { label: 'Sát thương chiêu', from: '210/315/475', to: '240/360/540' },
        { label: 'Sát thương mục tiêu cô lập', from: '255/385/575', to: '290/435/650' },
        { label: 'Số lần hạ gục để tiến hóa', from: '10/30/60/100', to: '8/30/60/100' },
      ],
    },
    {
      id: 'pbe0806-krug',
      category: 'champion',
      kind: 'nerf',
      name: 'Krug',
      cost: 3,
      entityId: 'champion:tft18_krug',
      changes: [
        { label: 'Khiên đánh dấu Alpha', from: '10%', to: '8%' },
        { label: 'Tỉ lệ máu thưởng Kruglette', from: '14%', to: '12%' },
        { label: 'Máu thưởng Kruglette (cố định)', from: '70/110/180', to: '50/100/180' },
        { label: 'Máu cộng thêm từ chiêu', from: '175/225/350', to: '175/225/325' },
      ],
    },
    {
      id: 'pbe0806-masteryi',
      category: 'champion',
      kind: 'nerf',
      name: 'Master Yi',
      cost: 3,
      entityId: 'champion:tft18_masteryi',
      changes: [{ label: 'Dạng SMPT — Sát thương chí mạng cộng dồn', from: '155/235/375', to: '145/220/350' }],
    },
    {
      id: 'pbe0806-rengar',
      category: 'champion',
      kind: 'nerf',
      name: 'Rengar',
      cost: 3,
      entityId: 'champion:tft18_rengar',
      changes: [
        { label: 'Sát thương chiêu', from: '295/445/710', to: '270/405/650' },
        { label: 'Hồi máu tối thiểu (theo SMPT)', from: '80/120/160', to: '70/100/130' },
        { label: 'Hồi máu tối đa (theo SMPT)', from: '180/270/360', to: '150/220/300' },
      ],
    },
    {
      id: 'pbe0806-vi',
      category: 'champion',
      kind: 'buff',
      name: 'Vi',
      cost: 3,
      entityId: 'champion:tft18_vi',
      changes: [{ label: 'Hồi máu tức thì', from: '200/250/350', to: '225/300/400' }],
    },

    // ── Tướng — 4 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0806-amumu',
      category: 'champion',
      kind: 'nerf',
      name: 'Amumu',
      cost: 4,
      entityId: 'champion:tft18_amumu',
      changes: [{ label: 'Tỉ lệ hồi máu theo máu tối đa', from: '2.4%', to: '2.2%' }],
    },
    {
      id: 'pbe0806-lillia',
      category: 'champion',
      kind: 'buff',
      name: 'Lillia',
      cost: 4,
      entityId: 'champion:tft18_lillia',
      changes: [{ label: 'Hồi máu', from: '250/325', to: '280/360' }],
    },
    {
      id: 'pbe0806-nidalee',
      category: 'champion',
      kind: 'buff',
      name: 'Nidalee',
      cost: 4,
      entityId: 'champion:tft18_nidalee',
      changes: [
        { label: 'Dạng SMCK — Sát thương vồ', from: '190/285/2500', to: '215/325/2500' },
        { label: 'Dạng SMCK — Hồi máu', from: '250/350/2000', to: '275/400/2000' },
        { label: 'Dạng SMPT — Sát thương đòn tăng cường', from: '135/205/2000', to: '160/240/2000' },
        { label: 'Dạng SMPT — Sát thương đòn đánh thứ 3', from: '250/375/3000', to: '300/450/3000' },
      ],
    },
    {
      id: 'pbe0806-sivir',
      category: 'champion',
      kind: 'buff',
      name: 'Sivir',
      cost: 4,
      entityId: 'champion:tft18_sivir',
      changes: [{ label: 'Sát thương chiêu', from: '155/235/1050', to: '165/250/1050' }],
    },
    {
      id: 'pbe0806-zyra',
      category: 'champion',
      kind: 'buff',
      name: 'Zyra',
      cost: 4,
      entityId: 'champion:tft18_zyra',
      changes: [{ label: 'Sát thương chiêu', from: '33/50/225', to: '35/52/225' }],
    },

    // ── Tướng — 5 vàng ──────────────────────────────────────────────
    {
      id: 'pbe0806-ashe',
      category: 'champion',
      kind: 'nerf',
      name: 'Ashe',
      cost: 5,
      entityId: 'champion:tft18_ashe',
      changes: [{ label: 'Năng lượng tối đa', from: '30/80', to: '30/90' }],
    },
    {
      id: 'pbe0806-draven',
      category: 'champion',
      kind: 'buff',
      name: 'Draven',
      cost: 5,
      entityId: 'champion:tft18_draven',
      changes: [{ label: 'Sát thương công cơ bản', from: '40', to: '48' }],
    },
    {
      id: 'pbe0806-elderdragon',
      category: 'champion',
      kind: 'nerf',
      name: 'The Elder Dragon',
      cost: 5,
      entityId: 'champion:tft18_elderdragon',
      changes: [{ label: 'Sát thương chiêu', from: '240/360', to: '200/300' }],
    },
    {
      id: 'pbe0806-lux',
      category: 'champion',
      kind: 'nerf',
      name: 'Lux',
      cost: 5,
      entityId: 'champion:tft18_lux',
      changes: [
        { label: 'Sát thương chiêu', from: '370/580', to: '330/520' },
        { label: 'Elderwood — Máu tối đa cộng thêm', from: '5%', to: '4%' },
        { label: 'Primal — Tốc đánh cộng thêm', from: '60%', to: '50%' },
      ],
    },
    {
      id: 'pbe0806-maokai',
      category: 'champion',
      kind: 'buff',
      name: 'Maokai',
      cost: 5,
      entityId: 'champion:tft18_maokai',
      changes: [{ label: 'Máu tối đa', from: '1000', to: '1100' }],
    },
    {
      id: 'pbe0806-taric',
      category: 'champion',
      kind: 'nerf',
      name: 'Taric',
      cost: 5,
      entityId: 'champion:tft18_taric',
      changes: [{ label: 'Khiên', from: '250/500', to: '200/400' }],
    },

    // ── Tộc hệ ──────────────────────────────────────────────────────
    {
      id: 'pbe0806-trait-blackthorn',
      category: 'trait',
      kind: 'rework',
      name: 'Blackthorn',
      entityId: 'trait:eldritch',
      changes: [
        { label: 'Hệ số x3 sao (2 vàng)', from: '300%', to: '280%' },
        { label: 'Hệ số x3 sao (3 vàng)', from: '400%', to: '330%' },
        { label: 'Mốc 2/4 — Máu cộng thêm (hi sinh Đỡ đòn)', from: '15%', to: '17%' },
        { label: 'Mốc 2/4 — Kháng chống chịu (hi sinh Đỡ đòn)', from: '15', to: '17' },
        { label: 'Mốc 2/4 — SMCK cộng thêm (hi sinh SMCK)', from: '20', to: '22' },
        { label: 'Mốc 2/4 — Tốc đánh cộng thêm (hi sinh SMCK)', from: '9%', to: '10%' },
        { label: 'Mốc 2/4 — Khuếch đại sát thương (hi sinh SMPT)', from: '12%', to: '13%' },
        { label: 'Mốc 2/4 — Hồi năng lượng (hi sinh SMPT)', from: '1.5', to: '1.7' },
        { label: 'Mốc 6 — Máu cộng thêm', from: '250', to: '200' },
        { label: 'Mốc 6 — Tốc đánh cộng thêm', from: '20%', to: '18%' },
        { label: 'Mốc 6 — SMCK cộng thêm', from: '20', to: '18' },
        { label: 'Mốc 6 — SMPT cộng thêm', from: '20', to: '18' },
        { label: 'Mốc 6 — Chỉ số chống chịu cộng thêm', from: '20', to: '15' },
      ],
    },
    {
      id: 'pbe0806-trait-coven',
      category: 'trait',
      kind: 'buff',
      name: 'Coven',
      entityId: 'trait:coven',
      breakpoint: '7',
      changes: [{ label: 'Tinh chất mỗi lần thua', from: '70', to: '100' }],
    },
    {
      id: 'pbe0806-trait-defender',
      category: 'trait',
      kind: 'buff',
      name: 'Defender',
      entityId: 'trait:defender',
      changes: [{ label: 'Kháng chống chịu tự thân', from: '25/55/110', to: '25/55/115' }],
    },
    {
      id: 'pbe0806-trait-eclipse',
      category: 'trait',
      kind: 'nerf',
      name: 'Eclipse',
      entityId: 'trait:eclipse',
      changes: [{ label: 'Chu kỳ kích hoạt', from: '3 giây', to: '4 giây' }],
    },
    {
      id: 'pbe0806-trait-elderwood',
      category: 'trait',
      kind: 'buff',
      name: 'Elderwood',
      entityId: 'trait:elderwood',
      changes: [
        { label: 'Cây Thạch Bì — Máu cộng thêm', from: '100', to: '150' },
        { label: 'Chiêu Người Bảo Hộ — Sát thương mục tiêu chính', from: '420/630', to: '445/670' },
        { label: 'Chiêu Người Bảo Hộ — Sát thương diện rộng', from: '210/315', to: '220/335' },
      ],
    },
    {
      id: 'pbe0806-trait-fae',
      category: 'trait',
      kind: 'buff',
      name: 'Fae',
      entityId: 'trait:fae',
      changes: [{ label: 'Ngưỡng phần thưởng Tiên Bụi Vàng', from: 'Ngưỡng cao hơn', to: 'Hạ ngưỡng (chưa công bố số cụ thể)' }],
    },
    {
      id: 'pbe0806-trait-juggernaut',
      category: 'trait',
      kind: 'buff',
      name: 'Juggernaut',
      entityId: 'trait:juggernaut',
      changes: [{ label: 'Độ bền tự thân', from: '20/28/34', to: '20/30/40' }],
    },
    {
      id: 'pbe0806-trait-solar',
      category: 'trait',
      kind: 'nerf',
      name: 'Solar',
      entityId: 'trait:solar',
      changes: [{ label: 'Hệ số cộng dồn theo tướng 3 sao', from: '2.5%', to: '1.5%' }],
    },
    {
      id: 'pbe0806-trait-vanguard',
      category: 'trait',
      kind: 'nerf',
      name: 'Vanguard',
      entityId: 'trait:vanguard',
      breakpoint: '6',
      changes: [{ label: 'Độ bền', from: '8%', to: '6%' }],
    },

    // ── Nâng cấp ────────────────────────────────────────────────────
    {
      id: 'pbe0806-aug-blossomscall',
      category: 'augment',
      kind: 'nerf',
      name: "Blossom's Call",
      entityId: 'augment:da_18_blossomtraitaugment',
      changes: [{ label: 'Vòng xuất hiện', from: 'Nhiều mốc', to: 'Chỉ 4-2' }],
    },
    {
      id: 'pbe0806-aug-bonusgift',
      category: 'augment',
      kind: 'nerf',
      name: 'Bonus Gift',
      entityId: 'augment:da_bonusgift',
      changes: [{ label: 'Tỉ lệ', from: '30%', to: '25%' }],
    },
    {
      id: 'pbe0806-aug-bonusgiftplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Bonus Gift +',
      entityId: 'augment:da_bonusgiftplus',
      changes: [{ label: 'Tỉ lệ', from: '30%', to: '25%' }],
    },
    {
      id: 'pbe0806-aug-champdelivery',
      category: 'augment',
      kind: 'nerf',
      name: 'Champ Delivery',
      note: '(+/++)',
      entityId: 'augment:da_champdelivery',
      changes: [{ label: 'Số vòng trễ', from: '4', to: '6' }],
    },
    {
      id: 'pbe0806-aug-crymeariver',
      category: 'augment',
      kind: 'buff',
      name: 'Cry Me A River',
      entityId: 'augment:da_crymeariver',
      changes: [{ label: 'Hồi năng lượng', from: '3', to: '4' }],
    },
    {
      id: 'pbe0806-aug-expedition',
      category: 'augment',
      kind: 'mechanic',
      name: 'Expedition',
      entityId: 'augment:da_expedition',
      changes: [{ label: 'Phần thưởng', from: 'Loot sai (bug)', to: '2 tướng 5 vàng + 1 nâng cấp masterwork + 1 component anvil' }],
    },
    {
      id: 'pbe0806-aug-flameon',
      category: 'augment',
      kind: 'buff',
      name: 'Flame On',
      entityId: 'augment:da_18_infernotraitaugment',
      changes: [{ label: 'Tốc đánh', from: '25%', to: '40%' }],
    },
    {
      id: 'pbe0806-aug-forgedinstrength',
      category: 'augment',
      kind: 'buff',
      name: 'Forged In Strength',
      entityId: 'augment:da_forgedinstrength',
      changes: [{ label: 'Số trang bị thành phần', from: '1', to: '2' }],
    },
    {
      id: 'pbe0806-aug-fourcing',
      category: 'augment',
      kind: 'buff',
      name: 'FOURcing',
      entityId: 'augment:da_18_fourcing',
      changes: [{ label: 'Máu', from: '85', to: '95' }],
    },
    {
      id: 'pbe0806-aug-investmentstrategy1',
      category: 'augment',
      kind: 'buff',
      name: 'Investment Strategy I',
      entityId: 'augment:da_investmentstrategyi',
      changes: [{ label: 'Vàng nhận ngay', from: '0', to: '4' }],
    },
    {
      id: 'pbe0806-aug-investmentstrategy2',
      category: 'augment',
      kind: 'buff',
      name: 'Investment Strategy II',
      entityId: 'augment:da_investmentstrategy',
      changes: [{ label: 'Vàng', from: '3', to: '8' }],
    },
    {
      id: 'pbe0806-aug-maxbuild',
      category: 'augment',
      kind: 'nerf',
      name: 'Max Build',
      entityId: 'augment:da_maxbuild',
      changes: [
        { label: 'Số lượt quay lại đầu', from: '12', to: '10' },
        { label: 'Số lượt quay ở cấp 9', from: '5', to: '3' },
      ],
    },
    {
      id: 'pbe0806-aug-quickstreaks',
      category: 'augment',
      kind: 'nerf',
      name: 'Quick Streaks',
      entityId: 'augment:da_quickstreaks',
      changes: [{ label: 'Vàng', from: '4', to: '2' }],
    },
    {
      id: 'pbe0806-aug-residualmagic',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic',
      entityId: 'augment:da_18_residualmagic',
      changes: [{ label: 'Máu', from: '100', to: '80' }],
    },
    {
      id: 'pbe0806-aug-residualmagicplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic +',
      entityId: 'augment:da_18_residualmagicplus',
      changes: [{ label: 'Máu', from: '130', to: '100' }],
    },
    {
      id: 'pbe0806-aug-residualmagicplusplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Residual Magic ++',
      entityId: 'augment:da_18_residualmagicplusplus',
      changes: [{ label: 'Máu', from: '150', to: '120' }],
    },
    {
      id: 'pbe0806-aug-shimmerscaleessence',
      category: 'augment',
      kind: 'nerf',
      name: 'Shimmerscale Essence',
      entityId: 'augment:da_shimmerscaleessence',
      changes: [{ label: 'Số vòng', from: '6', to: '7' }],
    },
    {
      id: 'pbe0806-aug-smallfurryfriend',
      category: 'augment',
      kind: 'nerf',
      name: 'Small Furry Friend',
      changes: [{ label: 'Hiệu quả giảm còn', from: '70%', to: '50%' }],
    },
    {
      id: 'pbe0806-aug-urf',
      category: 'augment',
      kind: 'buff',
      name: 'U.R.F',
      entityId: 'augment:da_urf',
      changes: [
        { label: 'Tốc đánh', from: '15', to: '20' },
        { label: 'Hồi năng lượng', from: '2', to: '3' },
      ],
    },
    {
      id: 'pbe0806-aug-wisprebate',
      category: 'augment',
      kind: 'nerf',
      name: 'Wisp Rebate',
      entityId: 'augment:da_18_wisprebateplus',
      changes: [{ label: 'Vàng', from: '6', to: '4' }],
    },
    {
      id: 'pbe0806-aug-wisprebateplus',
      category: 'augment',
      kind: 'nerf',
      name: 'Wisp Rebate +',
      entityId: 'augment:da_18_wisprebateplusplus',
      changes: [{ label: 'Vàng', from: '10', to: '8' }],
    },
  ],
};

export default report;
