// Draft bản vá LIVE 18.3 — bản cập nhật CHÍNH, tập trung Champs/Traits nhỏ
// gọn hơn 18.2 + buff diện rộng Augment giao tranh. Nội dung/số liệu đã soạn
// và duyệt trong Website/pbe-notes/Patch_TFT18.3-Live-main.md.
//
// Nguồn: patch note chính thức Riot, bản EN (toàn văn). Bản VI CHƯA xuất bản
// tại thời điểm soạn (404) — người dùng đã duyệt xử lý luôn với EN, dùng lại
// tên tiếng Việt sẵn có trong DB (không có thực thể mới phát sinh).
//
// Phạm vi cố ý KHÔNG đưa vào entries:
// - ~35 mục bugfix nhỏ (PvE spawn, Pandora's Bench, Carousel, tooltip, VFX) —
//   không có giá trị tra cứu số liệu. Chỉ giữ 1 mục (Augment UI minimize bug).
// - ~12 mục performance/stability PC+Mobile — không có số liệu before/after.
// - 34 vật phẩm trang trí chuyển đổi trong 18.3: không phải gameplay.
//
// Quyết định người dùng cho 3 điểm mơ hồ (xem .md mục "Vấn đề dữ liệu"):
// - Verticality: áp dụng cho cả 3 bậc (I/II/III).
// - "Stat Boosters" (Armor/MR Boost, Attack Speed Boost): không tìm được
//   entity số liệu khớp trong set18_wisps — ghi 1 entry mechanic không kèm
//   changes[] số liệu, không cập nhật codex.
// - "Thingamajig Wisps": có entity (Bag/Jar/Sack) nhưng thay đổi là xác suất
//   rơi loot, không có số liệu before/after — ghi 1 entry mechanic không kèm
//   changes[] số liệu, không cập nhật codex.
import type { PatchReport } from '../../../src/content/patch-notes';

const report: PatchReport = {
  id: 'patch-tft18-3',
  version: 'Live 23/09/2026 (18.3)',
  title: 'Bản cập nhật 18.3 — cân bằng gọn, buff Augment giao tranh',
  author: 'Baron TFT (dịch)',
  source: {
    label: 'Riot Games — patch note chính thức 18.3 (EN; bản VI chưa xuất bản)',
    url: 'https://teamfighttactics.leagueoflegends.com/en-us/news/game-updates/teamfight-tactics-patch-18-3/',
  },
  entitySet: 18,
  dateVi: '23/09/2026',
  summaryVi:
    'Bản cập nhật CHÍNH cỡ vừa, thu hẹp phạm vi so với 18.2 — chủ yếu nerf trần sức mạnh ở breakpoint cao nhất của Vệ Quân, Thợ Săn, Hỏa Ngục, Thuật Sĩ (đi kèm Ấn tương ứng) và 13 Tinh Linh hay splash cùng Hoa Linh (3), đổi lại buff Tiên Hắc Ám. Hồi sinh Wolf Bros (Warwick + Murkwolf) làm đội hình reroll cấp 6 nhờ buff cả hai. Karma, Alistar, Cassiopeia, Rammus, Azir, Lillia, Taric được buff để có chỗ đứng tốt hơn; Ornn và Veigar bị trảm bớt trần sức mạnh dù vẫn buff một phần sát thương cơ bản. Loạt Nâng Cấp giao tranh (Hold the Line, Spirit of Redemption, Jeweled Lotus I, Giant and Mighty...) được buff để cạnh tranh với Nâng Cấp kinh tế, trong khi Retribution bị nerf sau khi hưởng lợi từ buff Bàn Tay Công Lý ở 18.2. Nhiều bugfix cho PvE và sửa lỗi UI chọn Augment.',
  summaryOrigin: 'official',
  entries: [
    // ===== TỘC/HỆ =====
    {
      id: 'live183-trait-defender',
      category: 'trait',
      kind: 'nerf',
      entityId: 'trait:defender',
      name: 'Vệ Quân (Defender)',
      note: 'Chỉ nerf mốc cao nhất, nơi Ấn Vệ Quân cho quá nhiều giá trị.',
      changes: [
        { label: 'Chống Chịu (mốc cao nhất)', from: '120', to: '115' },
      ],
    },
    {
      id: 'live183-trait-hunter',
      category: 'trait',
      kind: 'nerf',
      entityId: 'trait:hunter',
      name: 'Thợ Săn (Hunter)',
      note: 'Chỉ nerf mốc cao nhất, các mốc thấp hơn giữ nguyên 20/30/40%.',
      changes: [
        { label: 'SMCK cộng thêm (mốc cao nhất)', from: '65%', to: '60%' },
      ],
    },
    {
      id: 'live183-trait-inferno',
      category: 'trait',
      kind: 'nerf',
      entityId: 'trait:inferno',
      name: 'Hỏa Ngục (Inferno)',
      note: 'Chỉ nerf 2 mốc cao nhất, 2 mốc thấp giữ nguyên 1/1%.',
      changes: [
        { label: 'Thiêu Đốt (2 mốc cao nhất)', from: '3.5% / 4.5%', to: '3% / 4%' },
      ],
    },
    {
      id: 'live183-trait-invoker',
      category: 'trait',
      kind: 'nerf',
      entityId: 'trait:invoker',
      name: 'Thuật Sĩ (Invoker)',
      note: 'Chỉ nerf mốc cao nhất, các mốc thấp giữ nguyên 3/4/6.',
      changes: [
        { label: 'Hồi Năng Lượng (mốc cao nhất)', from: '9', to: '8' },
      ],
    },
    {
      id: 'live183-trait-coven',
      category: 'trait',
      kind: 'buff',
      entityId: 'trait:coven',
      name: 'Tiên Hắc Ám (Coven)',
      note: 'Bù lại cashout quá dè dặt so với các tộc/hệ high-stakes trước đây; mốc cuối giữ nguyên 60.',
      changes: [
        { label: 'Tinh Túy mỗi lượt thua', from: '18/25/32', to: '22/28/35' },
      ],
    },

    // ===== WISP — nhóm "Blossom Charms" (nerf khi splash cùng Hoa Linh) =====
    {
      id: 'live183-wisp-animate-shop',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:animate-shop',
      name: 'Cửa Hàng Động (Animate Shop)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Thời gian', from: '26s', to: '24s' }],
    },
    {
      id: 'live183-wisp-blaze',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:blaze',
      name: 'Lửa Rừng Già (Blaze)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Sát thương', from: '1.5% Máu tối đa', to: '1.25% Máu tối đa' }],
    },
    {
      id: 'live183-wisp-blood-money',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:blood-money',
      name: 'Tài Lộc Từ Máu (Blood Money)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Giá', from: '1v', to: '2v' }],
    },
    {
      id: 'live183-wisp-combust',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:combust',
      name: 'Nổ Cảm Tử (Combust)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Sát thương', from: '22%', to: '18%' }],
    },
    {
      id: 'live183-wisp-curio-cart',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:curio-cart',
      name: 'Quầy Đồ Lạ (Curio Cart)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Vàng thưởng', from: '2v', to: '1v' }],
    },
    {
      id: 'live183-wisp-heated-rivalry',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:heated-rivalry',
      name: 'Kình Địch Nảy Lửa (Heated Rivalry)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Số lần Hạ Gục cần', from: '7', to: '5' }],
    },
    {
      id: 'live183-wisp-heroic-sacrifice',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:heroic-sacrifice',
      name: 'Hy Sinh Anh Dũng (Heroic Sacrifice)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [
        { label: 'SMCK/SMPT', from: '40%', to: '35%' },
        { label: 'Giáp/Kháng Phép', from: '40', to: '35' },
      ],
    },
    {
      id: 'live183-wisp-hugify',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:hugify',
      name: 'Khổng Lồ Hóa (Hugify)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Máu', from: '600', to: '500' }],
    },
    {
      id: 'live183-wisp-mana-rich-soil',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:mana-rich-soil',
      name: 'Bậc Thầy Thuật Sư (Mana-Rich Soil)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Giảm Năng Lượng', from: '25%', to: '20%' }],
    },
    {
      id: 'live183-wisp-mercenary-force',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:mercenary-force',
      name: 'Ngoại Binh (Mercenary Force)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Khuếch Đại Sát Thương', from: '4.5%', to: '4%' }],
    },
    {
      id: 'live183-wisp-moonlight-ritual',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:moonlight-ritual',
      name: 'Nghi Thức Ánh Trăng (Moonlight Ritual)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Giá', from: '2v', to: '3v' }],
    },
    {
      id: 'live183-wisp-sinister-deal',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:sinister-deal',
      name: 'Giao Kèo Hắc Ám (Sinister Deal)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [
        { label: 'Vàng', from: '3v', to: '2v' },
        { label: 'Máu mất', from: '3HP', to: '2HP' },
      ],
    },
    {
      id: 'live183-wisp-stand-alone',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:stand-alone',
      name: 'Đứng Một Mình (Stand Alone)',
      note: 'Nerf khi splash cùng Hoa Linh (3).',
      changes: [{ label: 'Máu/Sát thương cộng thêm', from: '22%', to: '20%' }],
    },

    // ===== WISP khác =====
    {
      id: 'live183-wisp-blood-and-iron',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:blood-and-iron',
      name: 'Máu Và Sắt (Blood and Iron)',
      changes: [{ label: 'Giá', from: '3v', to: '4v' }],
    },
    {
      id: 'live183-wisp-three-me',
      category: 'wisp',
      kind: 'nerf',
      entityId: 'wisp:three-me',
      name: 'Ba Chúng Tôi (Three Me)',
      changes: [{ label: 'Giá', from: '9v', to: '10v' }],
    },
    {
      id: 'live183-wisp-thingamajig',
      category: 'wisp',
      kind: 'mechanic',
      name: 'Túi Đồ Vặt (Thingamajig Bag/Jar/Sack)',
      note: 'Giảm khả năng cho Bình Hồi Năng Lượng khi mở — Riot không công bố số liệu xác suất before/after cụ thể.',
    },
    {
      id: 'live183-wisp-stat-boosters',
      category: 'wisp',
      kind: 'nerf',
      name: 'Vật phẩm tiêu thụ tăng chỉ số (Stat Boosters)',
      note: 'Giảm sức mạnh vật phẩm tiêu thụ ngẫu nhiên tăng Giáp/Kháng Phép và Tốc Độ Đánh (nguồn: Túi Bảo Bối và các phần thưởng tương tự).',
      changes: [
        { label: 'Giáp và Kháng Phép', from: '10', to: '8' },
        { label: 'Tốc Độ Đánh', from: '8%', to: '6%' },
      ],
    },

    // ===== TƯỚNG =====
    {
      id: 'live183-champ-karma',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_karma',
      cost: 1,
      name: 'Karma',
      changes: [{ label: 'Sát thương chiêu (Nổ)', from: '120/180/270/460 AP', to: '125/185/300/515 AP' }],
    },
    {
      id: 'live183-champ-ornn',
      category: 'champion',
      kind: 'nerf',
      entityId: 'champion:tft18_ornn',
      cost: 1,
      name: 'Ornn',
      note: '3 sao đang dễ dàng in Tạo Tác quá mức cho đội hình Mặt Trời ở late game; đảm bảo Ornn 2 sao không bị vạ lây.',
      changes: [
        { label: 'Thưởng Sức Mạnh Rèn (3★)', from: '+100%', to: '+85%' },
        { label: 'Ngưỡng Tạo Tác thứ 2', from: '155,000 Sức Mạnh Rèn', to: '140,000 Sức Mạnh Rèn' },
      ],
    },
    {
      id: 'live183-champ-veigar',
      category: 'champion',
      kind: 'nerf',
      entityId: 'champion:tft18_veigar',
      cost: 1,
      name: 'Veigar',
      note: 'Giảm scale theo mạng hạ gục (nguồn sức mạnh chính khi làm carry reroll với opener mạnh), đổi lại buff sát thương cơ bản để đỡ vô dụng khi không làm trung tâm đội hình.',
      changes: [
        { label: 'SMPT mỗi mạng hạ gục', from: '3%', to: '2%' },
        { label: 'Sát thương chiêu cơ bản', from: '175/265/395/670 AP', to: '200/300/450/765 AP' },
        { label: 'Sát thương chiêu cường hóa', from: '265/400/595/1015 AP', to: '300/450/675/1015 AP' },
      ],
    },
    {
      id: 'live183-champ-alistar',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_alistar',
      cost: 2,
      name: 'Alistar',
      changes: [
        { label: 'Hồi máu', from: '200/260/320 AP', to: '230/300/400 AP' },
        { label: 'Sát thương chiêu', from: '100/150/225 AP', to: '180/270/420 AP' },
      ],
    },
    {
      id: 'live183-champ-gromp',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_gromp',
      cost: 2,
      name: 'Gromp',
      note: 'Buff tác động mạnh hơn tới dạng SMCK, kèm buff nhẹ dạng SMPT.',
      changes: [
        { label: 'Sát thương theo thời gian (dạng SMPT)', from: '160/240/360 AP', to: '175/265/410 AP' },
        { label: 'Tốc Độ Đánh (dạng SMCK)', from: '0.7', to: '0.75' },
        { label: 'SMCK cơ bản (dạng SMCK)', from: '45', to: '50' },
      ],
    },
    {
      id: 'live183-champ-murkwolf',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_murkwolf',
      cost: 2,
      name: 'Murkwolf',
      note: 'Cùng Warwick hồi sinh Wolf Bros làm đội hình reroll cấp 6.',
      changes: [{ label: 'Sát thương đòn nhảy cường hóa', from: '60/90/135 AD', to: '65/100/160 AD' }],
    },
    {
      id: 'live183-champ-warwick',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_warwick',
      cost: 2,
      name: 'Warwick',
      note: 'Cùng Murkwolf hồi sinh Wolf Bros làm đội hình reroll cấp 6.',
      changes: [
        { label: 'Sát thương chiêu', from: '215/325/500 AD', to: '230/345/535 AD' },
        { label: 'Hồi máu', from: '20%', to: '25%' },
      ],
    },
    {
      id: 'live183-champ-azir',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_azir',
      cost: 3,
      name: 'Azir',
      changes: [{ label: 'Sát thương chiêu Lính Cát', from: '43/65/103', to: '46/69/110' }],
    },
    {
      id: 'live183-champ-cassiopeia',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_cassiopeia',
      cost: 3,
      name: 'Cassiopeia',
      note: 'Buff bù đắp sau khi Vệ Quân 6 (nguồn stall lớn của đội hình này) bị nerf.',
      changes: [{ label: 'Sát thương chiêu', from: '400/600/950', to: '425/630/1020' }],
    },
    {
      id: 'live183-champ-rammus',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_rammus',
      cost: 3,
      name: 'Rammus',
      changes: [{ label: 'Lá chắn', from: '350/450/550', to: '400/550/725' }],
    },
    {
      id: 'live183-champ-lillia',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_lillia',
      cost: 4,
      name: 'Lillia',
      changes: [{ label: 'Hồi máu', from: '325/475 AP', to: '350/525 AP' }],
    },
    {
      id: 'live183-champ-nidalee',
      category: 'champion',
      kind: 'rework',
      entityId: 'champion:tft18_nidalee',
      cost: 4,
      name: 'Nidalee',
      note: 'Sửa lỗi Giáp xuyên (đang 60% thay vì đúng 40%, hiển thị đổi 40%⇒60% nhưng KHÔNG đổi số thực tế); sát thương chiêu Dạng SMCK ghi bên dưới đã là con số SAU khi tính cả phần sửa lỗi này.',
      changes: [
        { label: 'Sát thương chiêu (Dạng SMCK)', from: '225/340 AD', to: '210/315 AD' },
        { label: 'Sát thương đòn đánh thứ 3 (Dạng SMPT)', from: '300/450 AP', to: '330/500 AP' },
      ],
    },
    {
      id: 'live183-champ-lux',
      category: 'champion',
      kind: 'buff',
      entityId: 'champion:tft18_lux',
      cost: 5,
      name: 'Lux',
      note: 'Chỉ áp dụng cho dạng Mặt Trời (Solar).',
      changes: [{ label: 'Thưởng sát thương mỗi 3★ (dạng Mặt Trời)', from: '12%', to: '15%' }],
    },
    {
      id: 'live183-champ-taric',
      category: 'champion',
      kind: 'rework',
      entityId: 'champion:tft18_taric',
      cost: 5,
      name: 'Taric',
      note: 'Giảm lá chắn thụ động cố định (không scale theo AP), tăng hồi máu kích hoạt để một chút AP tạo cảm giác hiệu quả hơn.',
      changes: [
        { label: 'Lá chắn nội tại cơ bản', from: '100/225', to: '75/150' },
        { label: 'Hồi máu kích hoạt', from: '250/375 AP', to: '275/450 AP' },
      ],
    },

    // ===== TRANG BỊ / TẠO TÁC =====
    {
      id: 'live183-item-goldcollector',
      category: 'item',
      kind: 'nerf',
      name: 'Đại Bác Hải Tặc (Gold Collector)',
      note: 'Patch note gọi tắt "The Collector" — cùng một trang bị.',
      changes: [{ label: 'SMCK', from: '40%', to: '35%' }],
    },
    {
      id: 'live183-item-eternalpact',
      category: 'item',
      kind: 'nerf',
      name: 'Khế Ước Vĩnh Hằng (Eternal Pact)',
      changes: [{ label: 'Năng Lượng khi Tank dùng chiêu', from: '15', to: '10' }],
    },
    {
      id: 'live183-item-statikkshiv',
      category: 'item',
      kind: 'buff',
      name: 'Dao Điện Statikk (Statikk Shiv)',
      changes: [{ label: 'SMPT cơ bản', from: '15%', to: '25%' }],
    },

    // ===== ẤN (EMBLEMS) =====
    {
      id: 'live183-item-brawleremblem',
      category: 'item',
      kind: 'buff',
      name: 'Ấn Đấu Sĩ (Brawler Emblem)',
      changes: [{ label: 'Sát thương', from: '2% Máu tối đa', to: '2.5% Máu tối đa' }],
    },
    {
      id: 'live183-item-hunteremblem',
      category: 'item',
      kind: 'nerf',
      name: 'Ấn Thợ Săn (Hunter Emblem)',
      changes: [{ label: 'SMCK mỗi mạng hạ gục', from: '18%', to: '15%' }],
    },
    {
      id: 'live183-item-invokeremblem',
      category: 'item',
      kind: 'nerf',
      name: 'Ấn Thuật Sĩ (Invoker Emblem)',
      changes: [{ label: 'Hồi Năng Lượng', from: '3', to: '2' }],
    },
    {
      id: 'live183-item-juggernautemblem',
      category: 'item',
      kind: 'nerf',
      name: 'Ấn Dũng Sĩ (Juggernaut Emblem)',
      changes: [{ label: 'Hồi Năng Lượng khi hạ gục', from: '15', to: '10' }],
    },

    // ===== NÂNG CẤP (AUGMENTS) =====
    {
      id: 'live183-aug-bonusgift',
      category: 'augment',
      kind: 'mechanic',
      entityId: 'augment:da_bonusgift',
      name: 'Quà Tặng Bất Ngờ (Bonus Gift/+)',
      note: 'Đổi tên hiển thị sang số nhiều "Bonus Gifts", không đổi hiệu ứng.',
    },
    {
      id: 'live183-aug-blossomscall',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_18_blossomtraitaugment',
      name: "Lời Mời Hoa Linh (Blossom's Call)",
      note: 'Giảm chi phí Tinh Linh tối thiểu cần thiết để thấy tướng 4 vàng ở các giai đoạn — dễ kích hoạt điều kiện hơn (đổi hướng so với nhãn "nerf" thô ở tên gọi số liệu).',
      changes: [
        { label: 'Chi phí Tinh Linh tối thiểu để thấy 4 vàng (giai đoạn 1)', from: '15/6/4/0v', to: '15/5/3/0v' },
        { label: 'Chi phí Tinh Linh tối thiểu để thấy 4 vàng (giai đoạn 2)', from: 'x/15/8/5/0', to: 'x/15/8/4/0' },
      ],
    },
    {
      id: 'live183-aug-challengersgrace',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_challengersgrace',
      name: "Ân Sủng Thách Đấu (Challenger's Grace)",
      changes: [{ label: 'Thời gian hiệu ứng', from: '3s', to: '4s' }],
    },
    {
      id: 'live183-aug-earlylearnings',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_earlylearnings',
      name: 'Học Sớm (Early Learnings)',
      changes: [{ label: 'SMCK/SMPT nền', from: '5%', to: '3%' }],
    },
    {
      id: 'live183-aug-electrochargei',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_electrochargei',
      name: 'Điện Giật I (Electrocharge I)',
      changes: [{ label: 'Sát thương theo giai đoạn', from: '30/50/70/90', to: '25/40/60/80' }],
    },
    {
      id: 'live183-aug-infinityprotection',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_infinityprotection',
      name: 'Bảo Vệ Vô Tận (Infinity Protection)',
      note: 'Vô hiệu hóa do lỗi.',
    },
    {
      id: 'live183-aug-itemextraction',
      category: 'augment',
      kind: 'rework',
      entityId: 'augment:da_blackthorntraitaugment',
      name: 'Khai Thác Trang Bị (Item Extraction)',
      changes: [
        { label: 'Số lần khai thác', from: '4', to: '3' },
        { label: 'Tướng tặng kèm', from: 'Veigar, Rek\'Sai', to: 'Azir, Veigar, Rek\'Sai' },
      ],
    },
    {
      id: 'live183-aug-itsmebaby',
      category: 'augment',
      kind: 'mechanic',
      entityId: 'augment:da_itsmebaby',
      name: "Cả Làng Cùng Vô Địch (It's Me, Baby)",
      note: 'Đổi tên ô trống được cường hóa từ "Spotlight" sang "Championship", không đổi hiệu ứng.',
    },
    {
      id: 'live183-aug-feelinglucky',
      category: 'augment',
      kind: 'mechanic',
      entityId: 'augment:da_feelinglucky',
      name: 'Vận May Mỉm Cười (Feeling Lucky)',
      note: 'Sửa lỗi: lật mặt Ngửa không còn cho dư 4 vàng ngoài dự kiến.',
    },
    {
      id: 'live183-aug-frontlinefoundation',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_frontlinefoundation',
      name: 'Nền Tảng Tiền Tuyến (Frontline Foundation)',
      note: 'Giờ có thể tặng Ấn Yorick + Ấn Dũng Sĩ.',
    },
    {
      id: 'live183-aug-futurefocused',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_futurefocused',
      name: 'Tập Trung Tương Lai (Future Focused)',
      changes: [{ label: 'Vàng', from: '8', to: '5' }],
    },
    {
      id: 'live183-aug-giantandmighty',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_giantandmighty',
      name: 'To Xác Và Mạnh Mẽ (Giant and Mighty)',
      changes: [{ label: 'Máu', from: '200', to: '225' }],
    },
    {
      id: 'live183-aug-grouphugi',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_grouphugi',
      name: 'Ôm Nhóm I (Group Hug I)',
      changes: [{ label: 'Chống Chịu', from: '6', to: '7' }],
    },
    {
      id: 'live183-aug-grouphugii',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_grouphugii',
      name: 'Ôm Nhóm II (Group Hug II)',
      changes: [{ label: 'Chống Chịu', from: '9', to: '10' }],
    },
    {
      id: 'live183-aug-heroicgrabbag',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_heroicgrabbag',
      name: 'Túi Quà Anh Hùng (Heroic Grab Bag)',
      changes: [{ label: 'Vàng khởi đầu', from: '4v', to: '6v' }],
    },
    {
      id: 'live183-aug-holdtheline',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_holdtheline',
      name: 'Giữ Vững Hàng Ngũ (Hold the Line)',
      changes: [
        { label: 'SMCK', from: '9%', to: '11%' },
        { label: 'SMPT', from: '10%', to: '11%' },
      ],
    },
    {
      id: 'live183-aug-jeweledlotusi',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_jeweledlotus_i',
      name: 'Hoa Sen Ngọc Bích I (Jeweled Lotus I)',
      changes: [{ label: 'Tỉ lệ Chí Mạng', from: '10%', to: '15%' }],
    },
    {
      id: 'live183-aug-retribution',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_retribution',
      name: 'Báo Ứng (Retribution)',
      note: 'Nerf để cân bằng lại sau khi hưởng lợi lớn từ buff Bàn Tay Công Lý (Hand of Justice) ở 18.2.',
      changes: [{ label: 'Tỉ lệ Chí Mạng', from: '25%', to: '15%' }],
    },
    {
      id: 'live183-aug-shimmerscaleessence',
      category: 'augment',
      kind: 'rework',
      entityId: 'augment:da_shimmerscaleessence',
      name: 'Tinh Túy Kim Long (Shimmerscale Essence)',
      changes: [
        { label: 'Số vòng trì hoãn', from: '8', to: '6' },
        { label: 'Trang bị đầu tiên', from: "Áo Giáp Đại Vương (Mogul's Mail)", to: "Lưỡi Kiếm May Mắn (Gambler's Blade)" },
        { label: 'Trang bị thứ hai', from: "Lưỡi Kiếm May Mắn (Gambler's Blade)", to: "Áo Giáp Đại Vương (Mogul's Mail)" },
      ],
    },
    {
      id: 'live183-aug-spiritofredemption',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_spiritofredemption',
      name: 'Tinh Thần Cứu Rỗi (Spirit of Redemption)',
      changes: [{ label: 'Hồi máu', from: '7.5%', to: '9%' }],
    },
    {
      id: 'live183-aug-upwardmobility',
      category: 'augment',
      kind: 'buff',
      entityId: 'augment:da_upwardmobility',
      name: 'Cơ Động Đi Lên (Upward Mobility)',
      changes: [{ label: 'Số lần reroll miễn phí khi lên cấp', from: '1', to: '2' }],
    },
    {
      id: 'live183-aug-verticality-i',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_verticalityi',
      name: 'Chiều Cao I (Verticality I)',
      note: 'Áp dụng cho cả 3 bậc — xem thêm Chiều Cao II/III.',
      changes: [{ label: 'Số tướng tối thiểu cùng tộc/hệ để được đề xuất', from: '(không giới hạn)', to: '4' }],
    },
    {
      id: 'live183-aug-verticality-ii',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_verticalityii',
      name: 'Chiều Cao II (Verticality II)',
      changes: [{ label: 'Số tướng tối thiểu cùng tộc/hệ để được đề xuất', from: '(không giới hạn)', to: '4' }],
    },
    {
      id: 'live183-aug-verticality-iii',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_verticalityiii',
      name: 'Chiều Cao III (Verticality III)',
      changes: [{ label: 'Số tướng tối thiểu cùng tộc/hệ để được đề xuất', from: '(không giới hạn)', to: '4' }],
    },
    {
      id: 'live183-aug-westicktogether',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_westicktogether',
      name: 'Đồng Lòng Sát Cánh (We Stick Together)',
      note: 'Không còn cho trùng 1 Ấn cho nhiều người chơi, không cho Ấn của tộc/hệ quá nhỏ, loại trừ Ấn Dũng Sĩ/Đấu Sĩ/Vệ Quân.',
    },
    {
      id: 'live183-aug-weighttheworth',
      category: 'augment',
      kind: 'nerf',
      entityId: 'augment:da_18_weighttheworth',
      name: 'Cân Đo Giá Trị (Weight the Worth)',
      note: 'Không còn tặng kèm 1 Máy Nhân Bản Tướng Nhỏ (Tiny Champion Duplicator).',
    },

    // ===== SỬA LỖI ĐÁNG CHÚ Ý =====
    {
      id: 'live183-mech-augmentuifix',
      category: 'mechanic',
      kind: 'mechanic',
      name: 'Sửa lỗi Augment UI',
      note: 'Nút thu nhỏ giao diện có thể vô tình huỷ Augment vừa chọn khi bấm ngay sau khi chọn — đã sửa.',
    },
  ],
};

export default report;
