"""Dựng lại Website/src/content/set18/set18-wisps.ts từ Set18/assets/wisps/wisps.json — bản
scrape DOM trực tiếp từ metatft.com/new-set#Wisps (176 linh hỏa, có category/tier/giá,
dữ liệu nâng cấp Hoa Linh, khoảng xuất hiện theo stage-round, điều kiện kích hoạt).

Khác với Set18/data/metatft_set18_vi.json (không có field "wisps"), đây là nguồn duy nhất có
đủ field cho thiết kế linh hỏa: icon phân loại theo category+tier, toggle "nâng cấp Hoa
Linh", khoảng xuất hiện.

## Vá lệch hàng Anh–Việt (2026-08-01)

Bản scrape gốc cào trang ở 2 ngôn ngữ thành 2 danh sách rồi ghép theo INDEX. Hai danh
sách đó được sắp xếp theo bảng chữ cái của chính ngôn ngữ mình, nên lệch nhau: 114/176
linh hỏa mang tên + mô tả tiếng Việt của một linh hỏa khác. Ví dụ `Counterspell`
(apiName `DA_18_Counterspell`) bị gán name_vi "Dư Chấn" — vốn là tên của `Aftershock`.
Đối chiếu với bảng charm trong Set18/data/metatft_set18_vi.json cho thấy:

    name_en / description_en / cost / tier / category  → khớp charm 176/176 (đúng)
    name_vi / description_vi / ...                     → khớp charm  62/176 (lệch)

Nên script KHÔNG còn đọc bất kỳ field `*_vi` nào từ file scrape. Toàn bộ phần tiếng Việt
được lấy lại từ bảng charm, khoá bằng `matched_charm.apiName` — nguồn có sẵn cả `name`
(VI) lẫn `name_en` cho từng apiName, nên ghép luôn đúng cặp:

    name_vi        ← charm[apiName].name
    description_vi ← charm[apiName].desc
    upgrade_vi     ← charm[apiName + "_Upgrade"].desc, dự phòng khớp theo desc_en
    appearsVi      ← dựng từ matched_charm.round_bounds (thay vì chuỗi DOM đã lệch)
    conditionsVi   ← dịch từ conditions_en (đã đúng hàng) qua CONDITION_PATTERNS

File scrape gốc Set18/assets/wisps/wisps.json được giữ nguyên — sửa ở bước dựng, không sửa
dữ liệu thô. Nếu lần sau scrape lại được cả 2 ngôn ngữ theo apiName thì bỏ hẳn phần vá.

## Điều kiện kích hoạt

conditions_en cào về dính liền không có dấu phân cách (vd "Have no 3-star championsBoard
value between 8 and 18First 15 seconds of planning"). CONDITION_SPLIT_RE chèn ranh giới
trước các từ khoá mở đầu quen thuộc (Have/Be/Not/At least/First/Board), CONDITION_PATTERNS
dịch từng khung câu, rồi tên tộc/hệ trong câu được thay bằng tên tiếng Việt lấy từ bảng
traits. Mẫu câu lạ không khớp rule nào thì giữ nguyên tiếng Anh (còn hơn dịch sai).

Chạy từ Website/: python scripts/update_wisps_from_scrape.py
(Set18/ không nằm trong git repo nào nên script sống ở đây, cạnh 3 script cùng loại.)
"""

import json
import re
from pathlib import Path

WEBSITE = Path(__file__).resolve().parent.parent


def find_set18() -> Path:
    """Set18/ nằm cạnh Website/ ở cây chính, nhưng khi script chạy trong git worktree
    (.claude/worktrees/<tên>/) thì WEBSITE.parent là thư mục worktrees chứ không phải
    thư mục gốc nữa. Đi ngược lên cho tới khi thấy một thư mục cạnh mình tên Set18 có
    chứa data/ — đúng ở cả hai trường hợp."""
    for base in [WEBSITE, *WEBSITE.parents]:
        candidate = base.parent / "Set18"
        if (candidate / "data").is_dir():
            return candidate
    raise SystemExit("Khong tim thay Set18/data khi di nguoc len tu " + str(WEBSITE))


SET18 = find_set18()
WISPS_JSON = SET18 / "assets" / "wisps" / "wisps.json"
CODEX_VI_JSON = SET18 / "data" / "metatft_set18_vi.json"
TS_OUT = WEBSITE / "src" / "content" / "set18" / "set18-wisps.ts"

TS_HEADER = """// GENERATED FILE — do not edit by hand.
// Generated by Website/scripts/update_wisps_from_scrape.py.

import type { Set18Wisp } from './set18-types';

export const set18Wisps: Set18Wisp[] = """

CATEGORY_VI = {
    "Champion": "Tướng",
    "Combat": "Giao Tranh",
    "GoldXP": "Vàng/Kinh Nghiệm",
    "Item": "Trang Bị",
    "Misc": "Khác",
    "Risky": "Mạo Hiểm",
    "Shop": "Cửa Hàng",
}

ROLE_VI = {
    "fighter": "Đấu Sĩ", "fighters": "Đấu Sĩ",
    "marksman": "Xạ Thủ", "marksmen": "Xạ Thủ",
    "caster": "Thuật Sư", "casters": "Thuật Sư",
    "tank": "Đỡ Đòn", "tanks": "Đỡ Đòn",
}

# thứ tự quan trọng: mẫu cụ thể hơn phải đứng trước mẫu chung chung.
CONDITION_PATTERNS = [
    (r"^Have at least (\d+) (\w+) on the board$", lambda m: f"Có ít nhất {m.group(1)} tướng {ROLE_VI.get(m.group(2), m.group(2))} trên bàn đấu"),
    (r"^Have an itemised (\w+)$", lambda m: f"Có 1 tướng {ROLE_VI.get(m.group(1), m.group(1))} đã trang bị đồ"),
    (r"^Have fielded (\d+) (\d+)-cost champions last combat$", lambda m: f"Đã ra sân {m.group(1)} tướng {m.group(2)} vàng ở trận trước"),
    (r"^Have a (\d+)-star (\d+)- or (\d+)-cost champion$", lambda m: f"Có 1 tướng {m.group(1)} sao, giá {m.group(2)} hoặc {m.group(3)} vàng"),
    (r"^Have at least (\d+) active traits$", lambda m: f"Có ít nhất {m.group(1)} tộc/hệ đang kích hoạt"),
    (r"^Have at least (\d+) gold$", lambda m: f"Có ít nhất {m.group(1)} vàng"),
    (r"^Have under (\d+) gold$", lambda m: f"Có dưới {m.group(1)} vàng"),
    (r"^Have at least (\d+) components? on the bench$", lambda m: f"Có ít nhất {m.group(1)} nguyên liệu ở băng ghế"),
    (r"^Have at least (\d+) components?$", lambda m: f"Có ít nhất {m.group(1)} nguyên liệu"),
    (r"^Have at least (\d+) 1-star champions?$", lambda m: f"Có ít nhất {m.group(1)} tướng 1 sao"),
    (r"^Have 2 1-star champions, or a fully itemised 5-cost$", lambda m: "Có 2 tướng 1 sao, hoặc 1 tướng 5 vàng đã trang bị đầy đủ"),
    (r"^Have 2 units with Precision$", lambda m: "Có 2 tướng mang Chuẩn Xác"),
    (r"^Have units of the required cost$", lambda m: "Có tướng đúng mức giá yêu cầu"),
    (r"^Have no 3-star champions$", lambda m: "Không có tướng 3 sao"),
    (r"^Have a unit on the bench$", lambda m: "Có 1 tướng ở băng ghế"),
    (r"^Have champions carrying items$", lambda m: "Có tướng đang mang trang bị"),
    (r"^Have fewer than (\d+) fully itemised units$", lambda m: f"Có ít hơn {m.group(1)} tướng đã trang bị đầy đủ"),
    (r"^Have (.+?) active$", lambda m: f"Có {m.group(1)} đang kích hoạt"),
    (r"^Have (.+?) inactive$", lambda m: f"Không có {m.group(1)} đang kích hoạt"),
    (r"^Board value between (\d+) and (\d+)$", lambda m: f"Tổng giá trị bàn đấu từ {m.group(1)} đến {m.group(2)}"),
    (r"^First (\d+) seconds of planning$", lambda m: f"Trong {m.group(1)} giây đầu vòng chuẩn bị"),
    (r"^Be missing (\d+) or more health$", lambda m: f"Mất từ {m.group(1)} máu trở lên"),
    (r"^Be above (\d+) health$", lambda m: f"Có trên {m.group(1)}% máu"),
    (r"^Be level (\d+) or above$", lambda m: f"Cấp độ {m.group(1)} trở lên"),
    (r"^Be on high health$", lambda m: "Đang có lượng máu cao"),
    (r"^Be on a short win streak$", lambda m: "Đang thắng liên tiếp (chuỗi ngắn)"),
    (r"^Be on a short loss streak$", lambda m: "Đang thua liên tiếp (chuỗi ngắn)"),
    (r"^Be on a win or loss streak$", lambda m: "Đang thắng hoặc thua liên tiếp"),
    (r"^At least (\d+) players remaining$", lambda m: f"Còn lại ít nhất {m.group(1)} người chơi"),
    # dùng đúng thuật ngữ hiển thị trong game: Shred = Cào Xé, Sunder = Phân Tách,
    # Wound = Vết Thương Sâu (bản cũ dịch là "Giảm Giáp"/"Phá Giáp"/"Suy Nhược").
    (r"^Not already applying Shred or Sunder$", lambda m: "Chưa áp Cào Xé hoặc Phân Tách lên mục tiêu"),
    (r"^Not already applying Burn or Wound, unless (.+?) is active$", lambda m: f"Chưa áp Thiêu Đốt hoặc Vết Thương Sâu lên mục tiêu, trừ khi {m.group(1)} đang kích hoạt"),
    (r"^Not for fully itemised manaless champions$", lambda m: "Không áp dụng cho tướng không dùng Năng Lượng đã trang bị đầy đủ"),
]

# ranh giới tách điều kiện dính liền — chèn xuống dòng trước các từ mở đầu quen
# thuộc khi chúng theo ngay sau chữ thường/số không có khoảng trắng.
CONDITION_SPLIT_RE = re.compile(r"(?<=[a-z0-9])(?=(?:Have|Be |Not |At least|First \d|Board value))")


def load_charm_index() -> tuple[dict, dict]:
    """apiName -> charm, và desc_en -> [charm] để dò biến thể nâng cấp khi thiếu _Upgrade."""
    codex = json.loads(CODEX_VI_JSON.read_text(encoding="utf-8"))
    by_api = {c["apiName"]: c for c in codex["charms"]}
    by_desc_en: dict[str, list] = {}
    for c in codex["charms"]:
        by_desc_en.setdefault((c.get("desc_en") or "").strip(), []).append(c)
    trait_vi = {
        t["name_en"]: t["name"]
        for t in codex["traits"]
        if t.get("name_en") and t.get("name") and t["name_en"] != t["name"]
    }
    return by_api, {"desc": by_desc_en, "trait": trait_vi}


def make_trait_localizer(trait_vi: dict):
    """Thay tên tộc/hệ tiếng Anh còn sót trong câu điều kiện bằng tên tiếng Việt.
    Ghép tên dài trước để "Apex Predator" không bị "Apex" nuốt mất."""
    if not trait_vi:
        return lambda s: s
    pattern = re.compile(r"\b(" + "|".join(re.escape(k) for k in sorted(trait_vi, key=len, reverse=True)) + r")\b")
    return lambda s: pattern.sub(lambda m: trait_vi[m.group(1)], s)


def translate_condition(fragment: str, localize_trait) -> str:
    for pattern, builder in CONDITION_PATTERNS:
        match = re.match(pattern, fragment)
        if match:
            return localize_trait(builder(match))
    return fragment


def build_conditions(conditions_en: str | None, localize_trait) -> list[str]:
    if not conditions_en:
        return []
    text = conditions_en.removeprefix("Requires:")
    fragments = [f.strip() for f in CONDITION_SPLIT_RE.split(text) if f.strip()]
    return [translate_condition(f, localize_trait) for f in fragments]


def build_appears(bounds: dict) -> str:
    """Dựng lại từ round_bounds thay vì dùng chuỗi "Appears:" cào từ DOM — chuỗi đó nằm
    ở phía tiếng Việt nên đã bị lệch hàng (có wisp hiện 3-1 đến 4-1 trong khi
    round_bounds thật là 2-1 đến 2-7)."""
    start, end = bounds.get("start"), bounds.get("end")
    if not start:
        return ""
    if end and end != start:
        return f"Xuất hiện: {start} đến {end}"
    return f"Xuất hiện: {start}"


def find_upgrade_charm(api: str, upgrade_desc_en: str | None, by_api: dict, by_desc_en: dict):
    """Charm bản nâng cấp Hoa Linh. 118/135 dùng hậu tố _Upgrade; số còn lại đặt apiName
    khác hẳn nên dò tiếp bằng desc_en (khớp tuyệt đối, ưu tiên charm cùng gốc apiName).

    Điều kiện vào cửa là wisp phải có `blossom_upgrade_description_en` — bảng charm có
    biến thể `_Upgrade` cho cả những linh hỏa KHÔNG hiện nút nâng cấp Hoa Linh trên web,
    nên nếu dò thẳng theo apiName sẽ gán nhầm bản nâng cấp cho 39 linh hỏa không có."""
    if not upgrade_desc_en:
        return None
    direct = by_api.get(f"{api}_Upgrade")
    if direct:
        return direct
    candidates = by_desc_en.get(upgrade_desc_en.strip(), [])
    if not candidates:
        return None
    same_root = [c for c in candidates if c["apiName"].startswith(api)]
    return (same_root or candidates)[0]


def remap_icon(category_icon: dict) -> str:
    fname = Path(category_icon["local_path"]).name
    return f"/set18/assets/wisp_categories/{fname}"


def build_wisp(w: dict, by_api: dict, by_desc_en: dict, localize_trait) -> dict:
    api = w["matched_charm"]["apiName"]
    charm = by_api[api]
    bounds = (w.get("matched_charm") or {}).get("round_bounds") or {}
    upgrade = find_upgrade_charm(api, w.get("blossom_upgrade_description_en"), by_api, by_desc_en)
    return {
        "name": w["name_en"],
        "nameVi": charm["name"],
        "category": w["category"],
        "categoryVi": CATEGORY_VI.get(w["category"], w["category"]),
        "categoryIcon": remap_icon(w["category_icon"]),
        "tier": w["tier"],
        "cost": w["cost"],
        "description": w["description_en"] or "",
        "descriptionVi": charm["desc"] or "",
        "blossomUpgradeCost": w["blossom_upgrade_cost"],
        "blossomUpgradeDescriptionVi": (upgrade["desc"] or None) if upgrade else None,
        "appearsVi": build_appears(bounds),
        "appearsStart": bounds.get("start"),
        "appearsEnd": bounds.get("end"),
        "conditionsVi": build_conditions(w["conditions_en"], localize_trait),
    }


def main() -> None:
    data = json.loads(WISPS_JSON.read_text(encoding="utf-8"))
    wisps = data["wisps"]
    by_api, extra = load_charm_index()
    localize_trait = make_trait_localizer(extra["trait"])

    icon_dir = WEBSITE / "public" / "set18" / "assets" / "wisp_categories"
    available = {p.name for p in icon_dir.iterdir()}
    missing_icons = sorted({Path(w["category_icon"]["local_path"]).name for w in wisps} - available)
    if missing_icons:
        raise SystemExit(f"Thieu icon phan loai: {missing_icons}")

    # dừng sớm nếu bảng charm không phủ hết — không có apiName thì không dựng lại được
    # phần tiếng Việt, mà im lặng bỏ qua sẽ đẻ ra tên rỗng trên web.
    unknown = sorted({w["matched_charm"]["apiName"] for w in wisps} - set(by_api))
    if unknown:
        raise SystemExit(f"Khong tim thay apiName trong bang charm: {unknown}")

    # bảng charm là nguồn tiếng Việt; chốt lại rằng phía tiếng Anh của file scrape
    # khớp bảng charm, nếu không thì matched_charm đã sai và cả bản vá vô nghĩa.
    mismatched_en = [w["name_en"] for w in wisps if by_api[w["matched_charm"]["apiName"]]["name_en"] != w["name_en"]]
    if mismatched_en:
        raise SystemExit(f"name_en lech so voi charm, matched_charm khong dang tin: {mismatched_en[:5]}")

    built = [build_wisp(w, by_api, extra["desc"], localize_trait) for w in wisps]
    built.sort(key=lambda w: (w["cost"] if w["cost"] is not None else 0, w["nameVi"]))

    TS_OUT.write_text(TS_HEADER + json.dumps(built, ensure_ascii=False) + ";\n", encoding="utf-8")

    fixed = sum(1 for w in wisps if by_api[w["matched_charm"]["apiName"]]["name"] != w["name_vi"])
    with_upgrade = sum(1 for w in built if w["blossomUpgradeDescriptionVi"])
    lost_upgrade = sum(1 for w in wisps if w.get("blossom_upgrade_description_en")) - with_upgrade
    print(f"Wrote {len(built)} wisps -> {TS_OUT.relative_to(WEBSITE)}")
    print(f"  {fixed} ten tieng Viet duoc sua lai tu bang charm (lech hang tu ban scrape)")
    print(f"  {with_upgrade} co mo ta nang cap Hoa Linh" + (f", {lost_upgrade} khong do duoc charm nang cap" if lost_upgrade else ""))


if __name__ == "__main__":
    main()
