// GENERATED FILE — do not edit by hand.
// Generated by Website/scripts/db/pull-set18.ts từ set18_augments/set18_wisps trên Neon.

export const set18VisibleCounts = {"augments":259,"wisps":175} as const;
