// GENERATED FILE — do not edit by hand.
// Generated by Website/scripts/db/pull-set18.ts từ bảng set18_tips trên Neon.

import type { Set18Tip } from './set18-types';

export const set18Tips: Set18Tip[] = [];
export const set18TipById = new Map(set18Tips.map((tip) => [tip.id, tip]));
